First version (without handler and tests)
CorporationX/url_shortener_service pull request #146
Opened 2024-05-17 11:27 UTC by gutorov

2024-05-19 09:55 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/controller/UrlShortenerController.java
> +@RequestMapping("/api/v1/url-shortener")
api v1 вынести в конфиг - это не пусть только этого контроллера, он общий вообще 
как, кстати, и url-shortener

2024-05-19 09:55 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/service/HashService.java
> +    }
а зачем тебе этот метод?

2024-05-19 09:55 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/service/UrlShortenerService.java
> +        //should I validate here if this url already exists in Repo??
не проверить надо, а вернуть хеш сразу, без сокращения - т.е достать и вернуть пользователю 
Он же этого и ждет 
Ему без разницы - есть у нас такой или нет, ему главное результат получить

2024-05-19 11:11 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +}
Да, просто у нас же еcть в теории еще Base8, Base10, Base18, Base32 . Вдруг мы захотим распоменять encoder и все нам. Да и в целом пытаюсь придерживаться LSP

2024-05-19 11:17 UTC, gutorov commented on src/main/resources/db/changelog/changeset/url_shortener__V001__initial.sql
> +    hash varchar(6) PRIMARY KEY,
у нас же у PRIMARY KEY два неявных CONSTRAINT это NOT NUL и UNIQUE, поэтому думаю излишне еще раз NOT NULL писать

2024-05-19 11:17 UTC, gutorov commented on src/main/resources/db/changelog/changeset/url_shortener__V001__initial.sql
> +    hash varchar(6) PRIMARY KEY
тоже самое)

2024-05-19 11:27 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/model/Hash.java
> +    private String hash;
А разве Spring JPA не делает тоже самое, то есть выставляет nullabale = flase
(по большей части риторический вопрос потому что я загуглил :)

2024-05-19 13:49 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/service/HashService.java
> +    }
Я почитал на открытых ресурсах: @Async и @Transactional вместе на одном методе не очень работают, из лучше разделить на разные

2024-05-19 13:58 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/service/UrlShortenerService.java
> +        //should I validate here if this url already exists in Repo??
Да, я понимаю, но тогда контрвопрос: если я без валидации буду ему отдавать хэш, то мне придется генерировать новый и там не будет далее иметь никакого смысла провдиться валидацию, потому что мне придется перезаписать значение хэша у этого URL в базе данных, что тоже будто бы не самое лучшее решение, или я что-то недопонимаю

2024-05-19 13:58 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/controller/UrlShortenerController.java
> +@RequestMapping("/api/v1/url-shortener")
сделав

2024-05-21 06:37 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/config/context/ExecutorConfig.java
> +    }
HashGeneratorPool - это назвать ExecutorService или про какой бин ты говоришь?

2024-05-21 06:38 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public CompletableFuture <List<Hash>> generateBatchAsync(){
тупанул, согласен, он же как @Transactional создает прокси

2024-05-21 09:43 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public CompletableFuture <List<Hash>> generateBatchAsync(){
Не совсем согласен: да, у меня есть ошибка в init методе где я его внутри вызываю, сейчас исправил на то, чтобы отдавать просто pool-у потоков на выполнение при инициализации, с помощью taskExecutor.execute(). Но в целом если вызывать его извне, то все будет работать) 

**Пруфы:**
<img width="1329" alt="Screenshot 2024-05-21 at 16 39 29" src="https://github.com/CorporationX/url_shortener_service/assets/115385337/8b10761e-c4c5-475c-a67e-c56dca73e9a4">
<img width="722" alt="Screenshot 2024-05-21 at 16 40 43" src="https://github.com/CorporationX/url_shortener_service/assets/115385337/5ffbe20e-20cb-4fb8-9b64-0112e1cf03b5">
<img width="1512" alt="Screenshot 2024-05-21 at 16 41 01" src="https://github.com/CorporationX/url_shortener_service/assets/115385337/0b0e4992-52d2-4791-a3a8-31e822d004f8">

2024-05-23 03:08 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/model/Url.java
> +    private String url;
Почему нет, везде, кроме айдишников, где они не нужны, вроде )

2024-05-23 03:15 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    List<Long> getUniqueNumbers(@Param("n") int batchSize);
оно работает, но да, лучше убрать парам)

2024-05-23 11:22 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    List<Hash> getHashBatch(int batchSize);
Работает все просто перфект, сам тестил )

2024-05-23 11:30 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    Hash findFirst();
Заменить на jpa я не смог, посмотрел документации, с гпт початился, но решения там готового не обнаружил. В целом этот метод у меня пока нигде не используется, я его делал только в рамках  пункта в задаче из джира.

2024-05-23 11:35 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/service/BaseEncoder.java
> +    }
Здесь переделал, как ты написала в прошлой раз, просто, я их добавляю в конкретную реализацию этого абстрактного класса. А здесь-то это как слой абстракции, то есть не желательно привязывать его к деталям)

2024-05-23 11:35 UTC, gutorov commented on src/main/java/faang/school/urlshortenerservice/config/context/ExecutorConfig.java
> +package faang.school.urlshortenerservice.config.context;
переделал)

2024-06-04 00:32 UTC, pablo023 requested changes
Отметил моменты, в целом также обращай внимание на кодстайл. Где-то отмечал это, где-то нет. На реальном проекте твои ПР будут возращаться из за отсутствия пробелов между круглой и фигурной скобкой, лишней пустой строки, и тд. Учись делать сразу хорошо, чтобы не переучиваться на работе.

2024-06-04 00:32 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/HashService.java
> +    public HashService(HashRepository hashRepository, UrlRepository urlRepository) {
ломбок

2024-06-04 00:32 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/HashService.java
> +        List<Url> urls = urlRepository.cleanOldHashes();
Когда ты выбираешь название для метода, думай о том, как это будет воспринимать человек, который читает код. Код гораздо меньше пишут, чем читают. Меня очень удивило, что метод, который чистит старые хэши, судя из названия, по итогу что-то возвращает. Это важнее, чем может показаться - сейчас проект небольшой, и ты в нем многое знаешь. Когда ты придешь на работу, проект будет гораздо больше, и там соблюдать такие правила критически важно. Тебе нужно обучиться таким образом, чтобы на работе ты получал положительный фидбек, и развивался. Подумай над этим моментом, отрефактори это.

2024-06-04 00:32 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlShortenerService.java
> +        //should I validate here if this url already exists in Repo??
Если ты хочешь выполнять проверку на уникальность хэша - выполняй её на уровне имплементации алгоритма. По принципу получил урл - сгенерировал хэш - проверил есть ли он в базе - если есть, то добавил к оригинальному урлу символ, и генерируешь новый. Тут важно только не сохранить так, чтобы сокращенный урл указывал на оригинальную ссылку, а не на ту, к которой ты подобавлял что-то.

2024-06-04 00:32 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlShortenerService.java
> +                () -> new EntityNotFoundException("Url with hash: " + hash + "not found!"));
Тут криво получится сообщния эксепшена, т.к. между хэшом и "not found" нет пробела

2024-06-04 00:32 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java
> +//    @Scheduled(fixedDelay = 10000)
Не оставляй это плиз

2024-12-22 21:03 UTC, closed without merging