feature-BC-6236 task made
CorporationX/url_shortener_service pull request #15
Opened 2023-10-01 16:36 UTC by OneWayMy

Поскольку задача с  получение хэша из HashCache еще не сделана то просто замокан HashCacheService

2023-10-08 16:44 UTC, kkkooolllyyyaaa requested changes
👍 , есть вопросы)

2023-10-08 16:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Изменяешь и возвращаешь тот же объект. Обычно, это антипаттерн, так делать не стоит)

2023-10-08 16:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        String hash = hashCacheService.getHash();
Это ты свободный hash получаешь?

2023-10-08 16:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        Url entity = save(entityToSave);
Я думаю стоит транзакционно достать по url из БД, вдруг там что-то уже лежит? Зачем на один и тот же url делать 2 сравнения

2023-10-08 16:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/model/Url.java
> +    private String url;
Если тут используешь String, то стоит перед сохранением всегда форматировать урл. Например, ты можешь сохранить 3 разные записи: "https://google.com", "google.com", "google.com/", хотя по сути это одно и то же)

2023-10-11 12:59 UTC, OneWayMy commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        String hash = hashCacheService.getHash();
Да, но поскольку задача не была сделана то замокал

2023-10-15 22:50 UTC, kkkooolllyyyaaa approved these changes
👍

2023-10-16 13:41 UTC, merged