Feature bc 6212
CorporationX/url_shortener_service pull request #3
Opened 2023-09-25 17:50 UTC by tarrasoff

2023-09-26 08:35 UTC, schonpink reviewed
Не увидела в конфиге liquibase - расположение файла с табл.

2023-09-26 08:35 UTC, schonpink commented on src/main/resources/db/changelog/changeset/url-shortener_V000__initial.sql
> +    INCREMENT 1
Только snake_case

2023-09-26 08:35 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    private String url;
тут мы можем хранить вообще любую длину url?

2023-09-26 08:35 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/entity/Hash.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Генерация хэшей у нас по заданию - с использованием последовательности - sequence, не уверена что тип IDENTITY тут подходит

2023-09-26 10:01 UTC, tarrasoff commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    private String url;
В миграцию добавил что длин может быть не более 4096 символов

2023-09-26 10:05 UTC, tarrasoff commented on src/main/resources/db/changelog/changeset/url-shortener_V000__initial.sql
> +    INCREMENT 1
Вот здесь не знаю где и что указать нужно

2023-09-27 09:22 UTC, InnMish requested changes

2023-09-27 09:22 UTC, InnMish commented on src/main/resources/db/changelog/changeset/url-shortener_V000__initial.sql
> +    hash       varchar(6) PRIMARY KEY NOT NULL,
Вот этот дружок - это ссылка на табличку hash, верно?
Если там hash это pk, то id Тоже не нужен)

2023-09-27 09:22 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    private String hash;
Это должна быть ссылка на сущность хэш  
У каждого юрл есть хэш, который мы ранее сгенерили

2023-09-27 09:22 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/entity/Hash.java
> +    private Long id;
А точно у нас сиквенс на айди должен быть? 
Суть сиквенс в том, чтобы в задаче Рамазана  можно было генерировать на основе этого всеглда уникального числа какой-то хэш 
Айди в этой сущности нам вообще по сути не нужно, только сам хэш
Его Рамазан сюда запишет (ну, его код точнее), сгенерированный на основе этого числа из последовательности. 
То есть к unique_number_sequence прям запрос нужно будет делать, а не к колонке привязывать)

2023-09-27 09:22 UTC, InnMish commented on src/main/resources/db/changelog/changeset/url-shortener_V000__initial.sql
> +    INCREMENT 1
к unique_number_seq мы должны иметь возможность просто обращаться за следующим числом 
Просто спросили - select next value и нам вернулось

2023-09-29 08:57 UTC, InnMish approved these changes

2023-09-29 08:57 UTC, merged