URL Shortener
CorporationX/url_shortener_service pull request #379
Opened 2024-09-12 17:10 UTC by kpzxpf

2024-09-17 04:31 UTC, pablo023 requested changes

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        List<Hash> hashes = urlRepository.deleteOlderOneYearUrls();
Мне не особо понятен вот этот момент. Ты сделал нативную кверю, которая идет в базу, удаляет оттуда залежавшиеся урлы, и возвращает их тебе. Зачем? А потом ты их после того, как удалил - опять туда сохраняешь. Это зачем мы так делаем?

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +        if (queueHashes.size() < (queueSize * (percentageToReplenishQueue / 100))) {
(queueHashes.size() < (queueSize * percentageToReplenishQueue) / 100) *

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +    public Hash getHash() {
Если ты используешь тут Async - тебе нужно либо войд, либо фючер, либо комплитбл фючер возвращать. Так асинк не используется.

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +    public Hash getHash() {
Либо ты можешь кинуть асинк на другой метод, который вот этот будет звать. Но вот так вот как сейчас - нет.

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +                hashGenerator.generateBatch();
А в очередь их не надо добавить после этого?

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            if (isGenerating.compareAndSet(false, true)) {
Вот до конкретно этого шага у тебя среда непотокобезопасная, и несколько потоков могут добраться до этого шага, чекнув размер твоей очереди, и потом уже один из них поставит тут, что генерация в процессе. Надо переделать.

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            throw new HashCacheException("Queue hashes is empty");
Тут поток не остановил. https://www.baeldung.com/java-interrupted-exception

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            return queueHashes.take();
Если очередь пустая, у тебя тут встанет всё, т.к. тейк заблокирует. Подумай над использованием альтернативных методов, например - полл с таймаутом.

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        if(!urlRepository.existsByUrl(url.getUrl())) {
Это не особо нужно, т.к. у тебя стоит констрейнт на то, что они уникальными могут быть только

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
Может быть нам после этого шага в кэш класть? А то мы так базу долбить можем почем зря

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
Не забудь readOnly убрать, если изменишь

2024-09-17 04:31 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    public void deleteOlderUrls() {
deleteUrlsOlderThanOneYear*

2024-09-17 07:49 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        List<Hash> hashes = urlRepository.deleteOlderOneYearUrls();
я возвращаю хеши чтобы их переиспользовать

2024-09-17 07:49 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +        if (queueHashes.size() < (queueSize * (percentageToReplenishQueue / 100))) {
ок

2024-09-17 08:06 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +    public Hash getHash() {
понял

2024-09-17 08:06 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +                hashGenerator.generateBatch();
поправил

2024-09-17 08:09 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            if (isGenerating.compareAndSet(false, true)) {
не очень понял в чем проблема, очередь же не пустая еще

2024-09-17 08:09 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            throw new HashCacheException("Queue hashes is empty");
понял

2024-09-17 08:09 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            return queueHashes.take();
ок

2024-09-17 08:11 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        if(!urlRepository.existsByUrl(url.getUrl())) {
там просто когда я тестил в базу не сохраняется, а в кэш сохраняется

2024-09-17 08:11 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    public void deleteOlderUrls() {
ок

2024-09-17 08:21 UTC, kpzxpf commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
можно

2024-09-19 04:25 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/сache/HashCache.java
> +            if (isGenerating.compareAndSet(false, true)) {
Зависит от количества потоков и их запросов, она может и опустеть

2024-09-24 00:06 UTC, merged