added required tables
CorporationX/url_shortener_service pull request #4
Opened 2023-09-26 15:35 UTC by AntonRudnikovskiy

2023-09-27 17:46 UTC, ringoway commented on src/main/resources/db/changelog/changeset/V001__url.sql
> +);
👍

2023-10-01 18:48 UTC, kkkooolllyyyaaa requested changes
Есть вопросики)

2023-10-01 18:48 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__url.sql
> +    hash varchar(20) PRIMARY KEY CHECK (LENGTH(hash) <= 6) NOT NULL,
Почему бы не сделать просто varchar(6) ? зачем отдельная проверка?

2023-10-01 18:48 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__url.sql
> +    url varchar(256),
Лучше text думаю) Можно потом нарваться на проблемы)

2023-10-01 18:48 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__url.sql
> +    created_at timestamptz DEFAULT current_timestamp
лучше без лишних дефолтов) Hibernate позаботиться о дефолте)

2023-10-01 18:48 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__url.sql
> +);
Лучше использовать стандартный sequence postgresql, зачем тебе эта таблица? Без primary key даже

2023-10-08 19:31 UTC, Rvze requested changes

2023-10-08 19:31 UTC, Rvze commented on gradlew
эти файлы нужно в .gitignore засунуть

2023-10-08 19:31 UTC, Rvze commented on src/main/java/faang/school/urlshortenerservice/entity/hash.java
> +public class hash {
класс с маленькой буквы?

2023-10-10 12:16 UTC, merged