Tests. BC-6503
CorporationX/url_shortener_service pull request #40
Opened 2023-10-09 15:00 UTC by Dlakares

2023-10-09 23:24 UTC, kkkooolllyyyaaa requested changes
Оставил комменты

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        return fillFactor <= hashes.size() / (capacity * 100);
как будто бы скобка не правильно расставлена

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    }
Думаю можно без этого усложнения)

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    }
мы тут пока ничего не оптимизируем типа)

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    @PostMapping("/shorten")
url/shorten мб? А то не понятно что там укорачивают)

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Ух-ты, а что это делает? Для чего этот эндпоинт?

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +    private String period; //Значение должно быть вида "y:m:w:d:h"
Можно же использовать Duration, и не мучаться так) 
Например PT1S или PT1H, погугли) Можно прям через @Value прочитать в объекте Duration

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public CompletableFuture<List<String>> generateBatch() {
А зачем CF если и так есть Async, или я чего-то не знаю?)

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Url not found"));
Тут по идее не IllegalArgumentException, а кастомное NotFound больше подходит) Хоть и пользователь передал не существующий hash, но всё же формат данных валиден.

2023-10-09 23:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                hash;
Лучше использовать классы URI, URL

2023-10-10 04:16 UTC, Dlakares commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Насколько я нашёл в интернете, этот метод редиректит. Но мне ошибиться, проверю сегодня ещё раз

2023-10-10 04:23 UTC, Dlakares commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    @PostMapping("/shorten")
Я посчитал, что раз это такой маленький сервис, то можно сделать так. Теперь, когда ты это отметил, задумался. Это же по сути апишка, а не юрлы сайта. По этому действительно, наверное надо ещё и маппинг сделать на отдельный юрл

2023-10-10 04:24 UTC, Dlakares commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    }
Можешь, пожалуйста, уточнить, что ты имеешь ввиду?

2023-10-10 04:24 UTC, Dlakares commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +    private String period; //Значение должно быть вида "y:m:w:d:h"
Спасибо, посмотрю и исправлю

2023-10-10 04:27 UTC, Dlakares commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public CompletableFuture<List<String>> generateBatch() {
Хм, ну асинк по сути всего лишь запускает задачу в многопоточке. Это значит, что результат этого метода может не быть сразу готов и может быть где то придётся подождать когда он завершится. По этому, CF. Разве не так?

2023-10-20 00:09 UTC, merged