Url shortner service grisatkac
CorporationX/url_shortener_service pull request #405
Opened 2024-09-14 21:44 UTC by grisatkac

2024-09-19 04:21 UTC, pablo023 requested changes

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +@Service
Repository, наверное?

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +            ps.setString(1, argument);
Вот это вот в трай-кетч надо, т.к. у тебя тут jdbcTemplate, и не предусмотрено поведение, которое должно быть, если коннекшен упадет, например. Хотя операция должна быть транзакционной

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                    .thenRun(() -> isFetching.set(false))
У тебя между выполнением реквестов очередь может опустошиться, если разные потоки здесь работают. По-хорошему, после добавления, проверить бы на пустоту твою очередь.

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public void generateBatch() {
Так как он асинхронный, несколько потоков могут его вызывать, и проделана будет твойная работа. Тут бы лок какой-то.

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepositoryJpa.java
> +    List<Hash> save(List<String> hashes);
Ты не должен возвращать ничего из квери, которая модифицирует. Modifying - про изменение, или удаление, но не про вставку. Вообще, нужно ли нам тут возвращать что-то?

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        while (number > 0) {
А если тебе пришел 0 сюда?

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    @Pattern(regexp = "^(https?|ftp):\\/\\/[^\\s/$.?#].[^\\s]*$\n", message = "Incorrect url format")
\n в конце точно нужен?

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/URLCacheRepository.java
> +        return Optional.ofNullable(redisTemplate.opsForValue().get(key));
Кладешь ты через opsForHash, вытаскиваешь - через opsForValue. Как-то неконсистентно. Может opsForHash().get? Или так и надо тут?

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                        log.error(String.format("Error during getting hashes, error message: %s", throwable.getMessage()));
String.format - блокирующая конструкция. Лучше просто используй тут фигурные скобки, в которые поместишь месседж из throwable.

2024-09-19 04:21 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private int minimumRequiredSize;
На будущее, лучше использовать ConfigurationProperties.

2024-09-22 21:53 UTC, grisatkac commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepositoryJpa.java
> +    List<Hash> save(List<String> hashes);
> Ты не должен возвращать ничего из квери, которая модифицирует. Modifying - про изменение, или удаление, но не про вставку. Вообще, нужно ли нам тут возвращать что-то?

я посмотрел и оказывается, что этот метод вообще нигде не используется
я для сохранения использую метод save из HashRepository класса батчами
поэтому удалю этот неиспользуемый квери

2024-09-22 22:26 UTC, grisatkac commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        while (number > 0) {
> А если тебе пришел 0 сюда?

если придёт 0, то преобразования данного числа не будет выполнено и из метода будет возвращена пустая строка
в таком случае,  я добавлю проверку, чтобы значения с пустой строкой отсеивались

2024-09-22 22:37 UTC, grisatkac commented on src/main/java/faang/school/urlshortenerservice/repository/URLCacheRepository.java
> +        return Optional.ofNullable(redisTemplate.opsForValue().get(key));
> Кладешь ты через opsForHash, вытаскиваешь - через opsForValue. Как-то неконсистентно. Может opsForHash().get? Или так и надо тут?

согласен) тут разницы нет, подправлю)

2024-09-23 03:29 UTC, merged