Full url-shortener feature
CorporationX/url_shortener_service pull request #435
Opened 2024-09-15 22:21 UTC by fokinms

BJS2-28029
BJS2-28030
BJS2-28031
BJS2-28032
BJS2-28033
BJS2-28034
BJS2-28035
BJS2-28036
BJS2-28037

2024-09-20 00:51 UTC, pablo023 requested changes

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        isGeneratingHash.set(true);
Вот тут у тебя несколько потоков могут зайти, и начать генерить батчи. Лучше бы чекать перед этим атомик булеан через if (isGeneratingHash.compareAndSet(false, true)), у тебя не будет состояния гонки тут тогда.

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            return cache.take();
Если очередь пустая, этот тейк заблокирует всё. Лучшей практикой является использование poll с таймаутом, и если не пришел хэш - логируешь, и кидаешь ошибку.

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +            throw new RuntimeException("Encoded string exceeds digits limit");
Своё надо писать исключение, Миш) Просто рантайм - несерьезно

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +        redisTemplate.opsForValue().set(key, value, Duration.ofDays(redisTtl));
Вот эту Duration.ofDays(redisTtl) можно сделать заранее, и не выполнять конвертацию при каждом сохранении. Например в постконструкт сделать её объектом ttlDuration, и сюда просто передавать.

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +    private final String base62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Ну это лучше в конфиг, всё таки.

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +                """;
Вообще, на будущее - оно пишется всегда капсом. Пиши капсом, иначе будут вопросы - где ты научился писать вот так, и тебе они не нужны)

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String query = "select nextval('unique_number_seq') as unique_numbers from generate_series(1, :quantity)";
Капсом

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String query = "insert into hash (hash) values(:hash)";
Капсом

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public void generateBatch() {
Так как это - асинк, у тебя оно где-то там в потоке, который это выполнять будет, может упасть. Лучшей практикой будет оборачивать такое в трай-кетч. И вообще, на будущее - научись создавать многопоточные тесты. Ошибки, связанные с concurrency - неочевидные, и мозг выедают, когда в проде случаются. Лучше быть уверенным хотя бы насколько то, что ты предусмотрел подлые сценарии, которые связаны с разными потоками.

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    private String url;
Можно еще валидацию на то, что это - действительно урл, через regex.

2024-09-20 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    @GetMapping("/{hash}")
Я могу ошибаться, но если я правильно понимаю, то при хэше "abc123" оно тебе тут вернет что-то типа localhost:6378/abc123/original-link. Поправь меня, если я не прав, либо себя, если не прав ты)

2024-09-20 07:42 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    @GetMapping("/{hash}")
Не, тут проверял все. Все правильно работает, редиректит. Внутри метода сервиса я иду за оригинальной ссылкой в кеш, если там нет то в базу, если и в базе нет то выбрасываю исключение, а возвращаю из метода RedirectView с параметром-ссылкой. т.е. либо исключение получаю, либо перенаправляюсь на страницу нужную

2024-09-20 10:03 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String query = "select nextval('unique_number_seq') as unique_numbers from generate_series(1, :quantity)";
Done

2024-09-20 10:06 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String query = "insert into hash (hash) values(:hash)";
Done

2024-09-20 10:09 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +                """;
Done

2024-09-20 10:09 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +                """;
Научился на буткемпе) изучая тонны разных мануалов) в таком стиле больше понравилось

2024-09-20 11:01 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            return cache.take();
так и сделал изначально) использовал take() как раз чтобы исключение не кидать)

2024-09-20 11:05 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        isGeneratingHash.set(true);
Done. Полезный метод, запомнил

2024-09-20 11:13 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +    private final String base62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Done

2024-09-20 18:41 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +            throw new RuntimeException("Encoded string exceeds digits limit");
Done

2024-09-20 19:19 UTC, fokinms commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public void generateBatch() {
Заведу привычку, спасибо. Таким способом достаточно решить проблему или как-то по-другому нужно сделать?

2024-09-22 02:16 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    public void generateBatch() {
Завернуть тут в трай-кетч будет достаточно, как хорошую практику

2024-09-22 02:17 UTC, merged