Url-shortener Final PullRequest
CorporationX/url_shortener_service pull request #461
Opened 2024-09-17 18:20 UTC by ravshanbekn

+ Имплементировал url-shortener

2024-09-23 03:27 UTC, pablo023 requested changes

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private Double CACHE_SIZE;
Капсом называем константы. У тебя тут не константа, они финальные.

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private Double CACHE_SIZE;
Кэш сайз не может быть дабл, тут инт по логике должен быть

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    public String getHash() {
тут в дабл закасти просто

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                lock.unlock();
Если в cacheHashes будет эксепшен, лок никогда не анлокнется. Используй файналли тут

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        hashCacheQueue.addAll(hashBatch);
addAll не работает с ArrayBlockingQueue, у нее ограниченная capacity, и этому методу это пофигу. Через цикл надо, с использованием offer.

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/hash/HashCacheConfig.java
> +    private Integer HASH_CACHE_THREAD_POOL_QUEUE_SIZE;
финальными их сделай, тогда это будут константы.

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/hash/HashCacheConfig.java
> +    private Integer HASH_QUEUE_SIZE;
Тут тоже

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/hash/HashConfig.java
> +    private Integer HASH_THREAD_POOL_QUEUE_SIZE;
Короче, везде исправь это

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Можно было бы, кстати, засунуть сюда проверку, что оригинальный урл начинается с https, и тем самым не допустить перехода на стрёмные урлы

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Ну это так

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/encoder/BaseEncoder.java
> +    private String alphabet;
final?

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private Duration SECONDARY_TIMEOUT;
final?

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private Duration SECONDARY_TIMEOUT;
Я бы их в постконстракте валидировал, что они не нуллы и тд

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            Optional<Url> urlOptional = urlRepository.findByHash(hash);
Сюда два потока могут пойти. Используй тут какой-нибудь атомик булеан с чек н сет

2024-09-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                throw new EntityNotFoundException("Could not find this redirecting url");
Ну тут можно сходить за урлом, как ты на 48 строке делаешь, и использовать там orElseThrow, почище будет код

2024-09-25 14:45 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private Double CACHE_SIZE;
Хорошо, можно ли обычным текстом тогда?

2024-09-25 14:46 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    public String getHash() {
Хорошо

2024-09-25 14:54 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                lock.unlock();
Сделал

2024-09-25 14:57 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        hashCacheQueue.addAll(hashBatch);
Хорошо

2024-10-03 10:07 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/config/hash/HashCacheConfig.java
> +    private Integer HASH_CACHE_THREAD_POOL_QUEUE_SIZE;
Исправил

2024-10-03 10:07 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/config/hash/HashCacheConfig.java
> +    private Integer HASH_QUEUE_SIZE;
Исправил

2024-10-03 10:07 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/config/hash/HashConfig.java
> +    private Integer HASH_THREAD_POOL_QUEUE_SIZE;
Ок

2024-10-03 10:10 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Хорошо

2024-10-03 10:11 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/encoder/BaseEncoder.java
> +    private String alphabet;
Если сделать final то через @ Value инжектить не получается

2024-10-03 16:51 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                throw new EntityNotFoundException("Could not find this redirecting url");
Хорошо

2024-10-03 16:51 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            Optional<Url> urlOptional = urlRepository.findByHash(hash);
Исправил

2024-10-03 17:17 UTC, ravshanbekn commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private Duration SECONDARY_TIMEOUT;
Сделал

2024-10-04 03:30 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private Double CACHE_SIZE;
Integer подойдет, вижу ты разобрался.

2024-10-04 03:31 UTC, merged