Brylev bjs2 27894
CorporationX/url_shortener_service pull request #463
Opened 2024-09-17 19:47 UTC by Caveri95

2024-09-23 03:12 UTC, pablo023 requested changes

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            return hashQueue.take();
Можешь дедлок поймать, если очередь пустая. Используй poll с таймаутом.

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/hashGenerator/Base62Encoder.java
> +        return builder.toString();
Ну он в обратном порядке тут выведет. Надо развернуть перед отдачей.

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/URLCacheRepository.java
> +    private final RedisTemplate<String, Object> redisTemplate;
У тебя же тут только стринги, зачем тебе значение Object?

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/URLCacheRepository.java
> +    }
Это будет работать, если редис не падает никогда. Если он упадёт - тут всё посыпется. Лучше в трай-кетч завернуть.

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            log.info("Getting url for hash {} from database", hash);
После того, как вытащили из базы, может, закэшировать её?

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    @Setter
Он нужен?

2024-09-23 03:12 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    @Setter
По моему, ты таким образом делаешь код небезопасным, сеттер то публичным будет

2024-09-25 12:32 UTC, Caveri95 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                            hashQueue.addAll(list);
окей, поправлю

2024-09-25 12:49 UTC, Caveri95 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        return hashQueue.size() / (cacheSize / 100) > percentToRefreshCache;
Да, ноль получается только из за того, что у меня все типы это int. Поставлю float на cacheSize и нуля не будет

2024-09-25 13:00 UTC, Caveri95 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            return hashQueue.take();
окей

2024-09-25 13:25 UTC, Caveri95 commented on src/main/java/faang/school/urlshortenerservice/repository/URLCacheRepository.java
> +    }
согласен

2024-09-25 13:50 UTC, Caveri95 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    @Setter
Сделан для того, чтобы в тестах указать значение поля

2024-09-29 01:48 UTC, merged