url-shortener full
CorporationX/url_shortener_service pull request #476
Opened 2024-09-18 20:17 UTC by fraifree

2024-09-22 02:57 UTC, pablo023 requested changes

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String sql = "INSERT INTO hash (hash) VALUES (?)";
У нас она каждый раз будет инициализироваться. Не лучший подход, ведь одно и то же каждый раз создаём. Может быть, где-то её было бы лучше один раз создать, и переиспользовать?

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String sql = "SELECT nextval('unique_number_seq') FROM generate_series(1, ?)";
Аналогично

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +                + ") AS sub WHERE hash.hash = sub.hash RETURNING hash.hash";
Аналогично

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        String sql = "SELECT COUNT(*) FROM hash";
Аналогично

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java
> +        String sql = "INSERT INTO url (hash, url, created_at, expired_at) VALUES (?, ?, ?, ?)";
Аналогично. Далее не буду дублировать, я бы все эти квери куда-то вынес.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .orElseThrow(() -> new EntityNotFoundException("No match found for: " + shortUrl));
Это - в отдельный приватный метод, чтобы мы здесь не создавали исключение. Вероятно, вытаскивать урлы по хэшу мы ещё будем, так что пусть будет отдельным методом.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/cashe/HashCache.java
> +            if (isFilling.compareAndSet(false, true)) {
За эту строчку у тебя может пойти, и популировать хэши только один поток. Но до этой строчки проверить, что размер твоей очереди меньше, либо равен минимальному, может сколько угодно потоков. В итоге один выйдет, и следующий пойдет популяцию производить, когда она уже, вроде как, и не нужна нам. Нужен механизм, который от этого защищать будет.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/cashe/HashCache.java
> +        System.out.println(queue.stream().findFirst());
Это ты, видимо, тестировал так. Замени логированием.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/hashegeneration/HashGenerator.java
> +            String value = hashes.remove(0);
У тебя каждая операция remove имеет линейную сложность. Думаю, надо отдельно почитать про временную сложность операций над списками, чтобы глубже понять. Если коротко - каждый раз выполняя remove с нулевого индекса, ты абсолютно все элементы в списке будешь сдвигать на 1 влево. Если там 1000 элементов у тебя, ты 999 операций совершишь ради вот этой итерации.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/config/hashegeneration/HashGenerator.java
> +            queue.add(value);
Используй offer, он безопаснее, и не позволит тебе выше крыши наливать в очередь, тебе не придется использовать этот while блок, ты сможешь просто forEach идти через список хэшей.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    public List<Long> getUniqueNumbers() {
Tranasctional?

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            String longUrl = Objects.requireNonNull(redisTemplate.opsForValue().get(shortUrl)).toString();
requireNonNull - удостоверивается, что программа не продолжит выполнение с нуллом. Здесь вылетит NPA сразу же, если что-то там не найдется. Поэтому, он нам тут сильно не поможет.

2024-09-22 02:57 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +import jakarta.persistence.*;
Измени у себя в IDE настройки импорта, чтобы у тебя никогда не импортировало всю любу. Поставь там, чтобы не тянуло всю, пока не вытянешь более 99 импортов.

2024-09-22 11:07 UTC, fraifree commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    public List<Long> getUniqueNumbers() {
Поставил в сервисе) Думаю да, она тут нужна, так как от этой операции зависит генерация хешей

2024-09-22 16:34 UTC, pablo023 commented
Отписать по поводу того, как правильно асинхронно получать оригинальный урл, и отправлять на создание короткий урл

2024-09-23 02:39 UTC, pablo023 commented
У тебя тут всё окей в плане того, как приложение будет обрабатывать запросы. Если ты хочешь добавить асинхронность - можешь пометить методы сервиса Async, и сделать возвращаемым значением CompletableFuture. Разницы не будет особой по факту, единственное - твой пользователь сможет одну за другой ссылки отправлять на генерацию / получение, не дожидаясь ответа. Я не думаю, что тебе это даже нужно здесь.

2024-09-23 15:52 UTC, fraifree commented
Понял, тогда не буду трогать

2024-09-24 19:16 UTC, merged