Titan master bc5 haiduk
CorporationX/url_shortener_service pull request #488
Opened 2024-09-19 08:21 UTC by shade2903

Full Task

2024-09-24 00:51 UTC, pablo023 requested changes

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +        if (queue.size() / (capacity / 100.0) < minFillPercent) {
1) В этот if могут зайти несколько потоков, получить тут true, пойти дальше, и встать в очередь. А потом один за другим пойдут наполнять очередь. Это уже неправильно.

2) Ты используешь addAll, а у него нет какого-то понимания того, что твоя LinkedBlockingDeque имеет ограниченный размер, и он может её переполнить. Посмотри метод offer. 

3) Используй не queue.size() в данном случае - он неатомарный, а remainingCapacity().

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +        return queue.poll().getHash();
Добавь в poll таймаут, т.к. если в очереди пусто, то мы не хотим тут заблокиоваться.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +        queue.addAll(hashGenerator.getBatch());
Исправь на offer.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +                isGenerating.set(false);
Учитывая, что наполняешь ты тут очередь асинхронно, у тебя может так получиться, что флаг isGenerating будет поставлен в true до того, как асинхронная задача отработает.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +                hashGenerator.getBatchAsync().thenAccept(queue::addAll);
Сюда бы добавить обработку исключения асинхронной задачи.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +    @Value("${hash.queue_capacity}")
Можно добавить дефолтное значение также, по-хорошему.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +import jakarta.persistence.*;
Не импортируй всю либу НИ КО ГДА. Исправь у себя в IDE, чтобы это не происходило автоматически, и знай - в проде на это внимание обращается всегда, и строго. Это важно знать, и не делать так.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private final HashCash hashCash;
HashCache*

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +public class HashCash {
HashCache

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +package faang.school.urlshortenerservice.cashe;
cache*. Cash это наличные деньги.

2024-09-24 00:51 UTC, pablo023 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        return entity.getUrl();
Может быть, её стоило бы закешировать, после того, как достали из базы?

2024-09-28 13:14 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +import jakarta.persistence.*;
Ок, поправил.

2024-09-28 13:22 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        return entity.getUrl();
Ок. Может в этом и есть резон. Добавил.

2024-09-28 14:04 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +package faang.school.urlshortenerservice.cashe;
Ок. Поправил.

2024-09-28 14:05 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private final HashCash hashCash;
Ок, поправил.

2024-09-28 14:32 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +    @Value("${hash.queue_capacity}")
Ок. Добавил.

2024-09-28 14:51 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +        queue.addAll(hashGenerator.getBatch());
Ок поправил.

2024-09-28 14:53 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +                hashGenerator.getBatchAsync().thenAccept(queue::addAll);
Добавил обработку исключения.

2024-09-28 14:54 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +                isGenerating.set(false);
Поправил условие проверки.

2024-09-28 16:36 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +        if (queue.size() / (capacity / 100.0) < minFillPercent) {
Поправил замечания

2024-09-28 16:36 UTC, shade2903 commented on src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java
> +        return queue.poll().getHash();
Ок, добавил.

2024-09-29 01:49 UTC, merged