BC-6214-1 Creating a short link
CorporationX/url_shortener_service pull request #49
Opened 2023-10-15 10:22 UTC by schonpink

2023-10-16 08:42 UTC, ipavelbel approved these changes
Пару моментов подметил.

2023-10-16 08:42 UTC, ipavelbel commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +        return urlService.shortenUrl(longUrl);
Возможно лучше будет возвращать  ResponseEntity.ok(shortUrl);  а не просто строку

2023-10-16 08:42 UTC, ipavelbel commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public void redirectToOriginalURL(@PathVariable String hash, HttpServletResponse response) {
точно ли произойдёт редирект ?

2023-10-16 08:42 UTC, ipavelbel commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +        return redisTemplate.opsForValue().get(CACHE_KEY + ":" + hash);
надо подумать что будет в случае если нету в редисе информации

2023-10-16 08:42 UTC, ipavelbel commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepositoryMock.java
> +public class UrlCacheRepositoryMock extends UrlCacheRepository {
Что-то не могу понять зачем нам  UrlCacheRepositoryMock

2023-10-16 08:42 UTC, ipavelbel commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        try {
видно код задублировался, или так надо? =)

2023-10-16 14:35 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepositoryMock.java
> +public class UrlCacheRepositoryMock extends UrlCacheRepository {
чисто для тестов

2023-10-19 06:22 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +        return redisTemplate.opsForValue().get(CACHE_KEY + ":" + hash);
переделала

2023-10-19 06:56 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public void redirectToOriginalURL(@PathVariable String hash, HttpServletResponse response) {
в тестах произошел

2023-10-23 07:54 UTC, InnMish requested changes

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +@RequestMapping("api/v1/url")
api/v1 давай перенесем в конфиги, как в остальных сервисах

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public void redirectToOriginalURL(@PathVariable String hash, HttpServletResponse response) {
Редирект - это другая задача 
Ее Паша, вроде бы, как раз делал, она на ревью висит сейчас

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public ResponseEntity<String> shortenUrl(@RequestBody UrlDTO urlDTO) {
А точно dto нужно? Там же только url и надо передать 
Может быть прям строчкой с первичной валидацией?

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +    private static final String CACHE_KEY_PREFIX = "url_cache:";
а зачем префикс? 
Мы в кэше храним ассоциацию хеш-юрл 
Эта строчка просто добавит к каждой записи еще два слова, есть какая-то цель у такого?

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +            redisUrlTemplate.expire(cacheKey, 48, TimeUnit.HOURS);
ttl может быть можно тут использовать, третьим параметром в opsForValue().set?

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +            return null;
А что мы тут поймаем? Метод не выбрасывает ничего, зачем try-catch?

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +        }
Будет ли ретрай работать вместе с catch? 
https://stackoverflow.com/questions/69630964/spring-retry-doesnt-work-with-a-try-catch-block

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    public String shortenUrl(String originalURL) {
зачем мы внутри ловим все подряд исключения? 
Мы ожидаем, что выпадет какая-то ошибка? Если да, то именно ее и обрабатываем, а если нет, то зачем этот блок? Если только для логирования, то надо проверять опытным путем - какая ошибка падает и именно ее ловить
А такая запись не очень чисто выглядит

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
а как так? Он же из конфига

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
И опять непонятная проверка

2023-10-23 07:54 UTC, InnMish commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
Что-то я не поняла, что тут происходит
у нас метод получения url Должен сначала поискать в редисе, потом в базе, если в редисе не нашел 
https://faang-school.atlassian.net/jira/software/c/projects/BC/boards/18?selectedIssue=BC-6210

2023-10-23 15:47 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public void redirectToOriginalURL(@PathVariable String hash, HttpServletResponse response) {
редирект у меня был в задании

2023-10-26 09:26 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
проверку убрала

2023-10-26 09:26 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
это убрала

2023-10-26 09:33 UTC, schonpink commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
Создаю объект matcher, который использует регулярное выражение, которое мы задали, для поиска соответствия входному короткому URL.

Если соответствие найдено, то matcher.group(1) возвращает  хэш; если не найдено, то выбрасывается исключение

2024-12-22 21:03 UTC, closed without merging