original link
CorporationX/url_shortener_service pull request #53
Opened 2023-10-17 17:31 UTC by M1hasMAD

1. прошу уделить внимание на возвращаемый тип в контроллере и сервисе, если нужно дтошку, то поправлю
2. насчет 302 http ответа, достаточно ли будет аннотации над методом?

2023-10-20 00:33 UTC, kkkooolllyyyaaa requested changes
Надо поправить

2023-10-20 00:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    }
Работает ведь?)

2023-10-20 00:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .orElseThrow(() -> new UrlNotFoundException("Not found URL from cache"));
by hash %s дописать бы) Иначе не оч информативно

2023-10-20 00:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .orElseThrow(() -> new UrlNotFoundException("Not found URL from DB"));
by hash %s дописать бы) Иначе не оч информативно

2023-10-20 00:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        if (urlFromDb != null) {
Условие же лишнее. У тебя же сверху есть orElseThrow. Снизу исключение поэтому бросать не нужно

2023-10-20 11:39 UTC, M1hasMAD commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .orElseThrow(() -> new UrlNotFoundException("Not found URL from cache"));
а если ли разница между:
String.format("Not found URL from cache by hash %s", hash)
и 
"Not found URL from cache by hash + " + hash?

2023-10-24 00:49 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .orElseThrow(() -> new UrlNotFoundException("Not found URL from cache"));
функционально нет, но 1 формат гибче поддерживается при изменениях)

2023-10-24 00:49 UTC, kkkooolllyyyaaa approved these changes
👍

2023-10-24 00:49 UTC, merged