Initial commit for BJS2-42593
CorporationX/url_shortener_service pull request #558
Opened 2024-11-11 18:27 UTC by soulasphyxia

Задачи:
* Создать структуру БД
* Работа с базой(HashRepository)
* Генерация списка хэшей
* Генерация хэша

2024-11-13 08:58 UTC, ArstanSubanov approved these changes
👍

2024-11-13 08:58 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +        for (int i = 0; i < 6; i++) {
Как смотришь на то, чтобы 6 вынести в properties? Конечно вряд ли что длина строк может быть больше, но если считать как считал Влад в лекции, то можно вроде начать и с 5 символов, а потом, посмотреть на нагрузки и увеличить число символов, если понадобится, мне кажется так можно сэкономить немного памяти)

2024-11-13 08:58 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +            result.append(ALPHABET.charAt((int) (number % 62)));
Число 62 в константы?)

2024-11-13 13:13 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +            result.append(ALPHABET.charAt((int) (number % 62)));
можно alphabet.size написать, так думаю лучше будет, тогда можно и алфавит вынести в конфиг)

2024-11-13 13:13 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +        for (int i = 0; i < 6; i++) {
я думал да про все это, но у нас вроде как в бд тоже захардкожено что длина 6 будет

2024-11-13 18:59 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +            regexp = "((?<SCHEME>https?)(?<HOSTNAME>://(?:www.|[a-zA-Z.]+)[a-zA-Z0-9\\-.]+\\.(?:biz|ca|com|edu|gov|info|me|mil|museum|name|net|org|uk|ru|us))?(?<PORT>:[0-9][0-9]{0,4}|[1-5][0-9]{4}|6[
хотел это вынести как-то, не понял как

2024-11-14 00:28 UTC, SharkB38 approved these changes

2024-11-14 18:27 UTC, mysosnovskaya requested changes
Жду тестов, в остальном - отличная работа!)

2024-11-14 18:27 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/url_shortener_V001_initial.sql
> +  hash varchar(6) PRIMARY KEY CHECK (length(hash) = 6),
У нас же может быть меньше шести?

2024-11-14 18:27 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/executor/ExecutorService.java
> +            writeLock.lock();
Зачем нужен лок? Ведь ArrayBlockingQueue потокобезопасная коллекция

2024-11-14 18:27 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +    private final RedisTemplate<String, String> redisTemplate;
Кстати, у спринта для редиса есть такие же готовые репозитории, как и для баз данных
https://docs.spring.io/spring-data/redis/reference/redis/redis-repositories/usage.html
В этой задаче хорошо и в текущем виде смотрится, т.к. нам в редисе нужно хранить просто строку, а не объект,  но просто захотелось поделиться, если вдруг ты об этом не знал :)

2024-11-15 09:48 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java
> +    private final RedisTemplate<String, String> redisTemplate;
да, я читал про это, но решил что так удобнее будет) спасибо!

2024-11-15 10:25 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java
> +        WHERE u.created_at < now() - interval '365 days'
я попытался вынести, когда выполняется запрос ругается, что ошибка синтаксиса (судя по запросу, надо передать в кавычках интервал), я его форматировал, передавал так, пытался кастить, не получилось( если хочется так вынести, наверное надо смотреть как другой запрос писать

2024-11-15 10:26 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java
> +    private final HashRepository hashRepository;
да, я задумался, когда на дейлике говорили, но решил не переделывать

2024-11-15 10:26 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/service/UrlServiceImpl.java
> +    public UrlResponse save(UrlDto urlDto) {
да, я не подумал об этом, сделаю

2024-11-15 11:00 UTC, soulasphyxia commented on src/main/resources/db/changelog/changeset/url_shortener_V001_initial.sql
> +  hash varchar(6) PRIMARY KEY CHECK (length(hash) = 6),
думаю может, соглашусь, тогда какое-то странное ограничение

2024-11-15 11:33 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepositoryImpl.java
> +    @Value("${hash.repository.batch.batch-size}")
я по задаче делал, там так методы описаны были. это n также потом задается через конфиг в hash генераторе, но соглашусь, как то странно получается

2024-11-15 11:36 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/executor/ExecutorService.java
> +        hashGenerator.generateBatch();
хэшей всегда хватит, но они будут просто лежать и занимать много памяти) согласен, наверное стоит добавить какой-то параметр, который бы проверял сколько всего хэшей и если их слишком много то не стоит дополнительно их генерировать

2024-11-15 11:52 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +    @Value("${hash.encoder.alphabet}")
да, тут как то слишком универсально получилось, хотя класс должен оперировать конкретными константами

2024-11-16 09:21 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/executor/ExecutorService.java
> +    public void fillCache(ArrayBlockingQueue<String> cache) {
согласен, переделаю

2024-11-16 09:32 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/executor/ExecutorService.java
> +    public void fillCache(ArrayBlockingQueue<String> cache) {
согласен, переделаю!

2024-11-16 09:34 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/executor/ExecutorService.java
> +            writeLock.lock();
у меня без лока каждый поток начинал генерацию хэшей, хотя это нужно делать 1 раз. посмотрел лекцию, Влад решил это через AtomicBoolean, переделал также

2024-11-16 09:49 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/service/UrlServiceImpl.java
> +    public UrlResponse save(UrlDto urlDto) {
я сел делать и подумал, насколько это вообще надо? как я понимаю, с текущей структурой (key: hash, value: url) сделать быстрый поиск по value не совсем тривиальная задача. мне приходит в голову только сохранять в кэш обратную запись (key: url, value: hash), что x2 забивает кэш сто процентов, но может да быть ситуация что в кэше будет очень много одинаковых записей и он будет еще больше забит. не знаю, что лучше... если взять пример сокращателя ссылок от яндекс (clck.ru), там короткая ссылка генерируется для одинакового урла разная. мне кажется сокращатель ссылок используется для довольно больших ссылок и какая вероятность что они будут настолько часто идентичны, чтобы кэшировать их?

2024-11-16 19:09 UTC, mysosnovskaya reviewed
Остались совсем мелочи)

2024-11-16 19:09 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +        if (hashRepository.getHashCount() == 0) {
Костыль?) У тебя всё равно несколько микросервисов могут выполнить эту проверку, увидеть, что в базе 0 хэшей и начать генерировать их. В целом я никакой проблемы в этом не вижу - пусть генерируют одновременно

2024-11-16 19:09 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +    private int batchSize;
Сначала все поля, а потом все методы. А у тебя метод init выше этого поля располагается

2024-11-16 19:09 UTC, mysosnovskaya commented on src/test/resources/db/test_url_schema.sql
> +INSERT INTO url(hash, url) VALUES ('100000', 'https://faang-school.com/courses') ON CONFLICT DO NOTHING;
Хоть это и тест, а тестовые данные всё равно должны быть правдоподобными. Сделать хэш похожим на настоящий - с буквами)

2024-11-17 08:08 UTC, soulasphyxia commented on src/test/resources/db/test_url_schema.sql
> +INSERT INTO url(hash, url) VALUES ('100000', 'https://faang-school.com/courses') ON CONFLICT DO NOTHING;
это настоящий хэш для числа 1 :)

2024-11-17 08:11 UTC, soulasphyxia commented on src/test/resources/db/test_url_schema.sql
> +INSERT INTO url(hash, url) VALUES ('100000', 'https://faang-school.com/courses') ON CONFLICT DO NOTHING;
Влад говорил, что для красоты можно начать генерировать последовательность с какого-то достаточного большого числа, чтобы были красивые хэши, но это необязательно

2024-11-17 08:42 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/service/UrlServiceImpl.java
> +    public UrlResponse save(UrlDto urlDto) {
да, в базе согласен, сделаю!

2024-11-17 08:47 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +        if (hashRepository.getHashCount() == 0) {
да, это костыль...

2024-11-17 20:16 UTC, mysosnovskaya requested changes
Мне не хватило тестов на репозитории (UrlRepository и HashRepositoryImpl). Там есть сложные sql запросы и нужно с помощью тестов убедиться, что они работают корректно. Можно написать интеграционные тесты через SpringBootTest, а для jpa репозиторий можно использовать аннотацию DataJpaTest (необязательно, можно и через SpringBootTest)

2024-11-17 20:16 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +        if (hashRepository.getHashCount() == 0) {
Вообще это был намек на то, что его нужно удалить =)

2024-11-17 20:16 UTC, mysosnovskaya commented on src/test/resources/db/test_url_schema.sql
> +INSERT INTO url(hash, url) VALUES ('100000', 'https://faang-school.com/courses') ON CONFLICT DO NOTHING;
Да я понимаю, что настоящий, но если брать глобально все хэши, которые мы можем сгенерировать, то хэш из одного элемента можно предполагать, что никогда нам не попадется (вероятность этого события стремится к нулю, можно считать равной нулю). А уже тем более из одной цифры. Поэтому лучше брать более общие сценарии, когда хэш состоит хотя бы из 4 элементов и в нем есть и буквы (большие и маленькие), и цифры

2024-11-17 20:16 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/controller/UrlControllerIT.java
> +                .andExpect(status().isOk());
Проверить бы, что вернулся какой-то хэш, что в базе данных что-то появилось. Можно даже проверить, что последовательно в бд увеличилась на 1. А то у тебя сейчас тест практически ничего и не проверяет. Статус 200 мог вернуться даже тогда, когда в действительности вообще ничего не произошло, просто пустой void метод. 
К тому же нужно проверить ситуацию, когда в базе уже был хэш для этого урла. Тогда наоборот - последовательность увеличится не должна и в базе данных не должны появиться новые записи

2024-11-17 20:16 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +    @Async("taskExecutor")
А может быть такое, что метод завершится ошибкой и в базе данных будет 0 хэшей? Что тогда будет?

2024-11-19 15:16 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +    @Async("taskExecutor")
мне кажется эту ошибку легко избежать если поанализировать соотношение генерируемых хэшей и забираемых, тогда в базе будет настолько много хэшей что они никогда не закончатся. такая проблема может возникнуть только при старте приложения, но я вроде сделал синхронное заполнение при запуске, поэтому все точно должно быть ок

2024-11-19 15:16 UTC, soulasphyxia commented on src/test/java/faang/school/urlshortenerservice/controller/UrlControllerIT.java
> +                .andExpect(status().isOk());
последовательность для этой таблицы не генируется(там id это хэши), проверил просто через findAll) можно было отдельно запрос написать но я подумал для тестовой базы так тоже пойдет

2024-11-19 15:40 UTC, soulasphyxia commented on src/test/java/faang/school/urlshortenerservice/repository/HashRepositoryTest.java
> +    public void testGetUniqueNumbers() {
хотелось проверить что последовательность действительно увеличивается на число, которое мы сгенерили, но у меня не получалось из-за того что при инициализации HashCache генерировались еще хэши и почему то перед вызовом метода было 100 хэшей, а потом становилось 205(100 с инициалзиации кэша из-за того что не пройден лимит, 5 мы просили), пофиксил тем, что при инициализации HashGenerator генерируется сразу лимит и тогда кэш просто заполняется. вроде помогло, последовательность стала вести себя ожидаемо.
но появилась другая проблема: я инжектил в тестовый класс JdbcTemplate и черзе него делал запрос на currval последовательности. когда запускал только этот тест то все было ок, оно отрабатывало, но когда я тестирую класс, то тест вылетает ошибка: "StatementCallback; uncategorized SQLException for SQL [select currval('unique_number_seq')]; SQL state [55000]; error code [0]; ERROR: currval of sequence "unique_number_seq" is not yet defined in this session". я пытался гуглить но не понял в чем проблема

2024-11-19 15:48 UTC, soulasphyxia commented on src/test/java/faang/school/urlshortenerservice/repository/HashRepositoryTest.java
> +    public void testGetUniqueNumbers() {
вроде пофиксил, изменив currval на last_value

2024-11-19 19:42 UTC, mysosnovskaya approved these changes
Давай костыль удалим всё-таки) И можешь сам смержить

2024-11-19 19:42 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/controller/UrlControllerIT.java
> +                .andExpect(status().isOk());
Да, так нормально

2024-11-19 19:42 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java
> +        if (hashRepository.getHashCount() == 0) {
Так и не получилось написать тест подходящий? Кстати говоря, если тебе эта строка нужна только для тестов, то тебе не нужна эта строка) Тесты не должны влиять на основной код

2024-11-21 13:03 UTC, merged