feature-BJS2-42663: Создать структуру БД
CorporationX/url_shortener_service pull request #559
Opened 2024-11-11 19:46 UTC by StepnovaVarvara

2024-11-12 08:26 UTC, Silencemess1ah commented
Все гут! А я без constraint сделал

2024-11-12 11:04 UTC, GusevVrn commented
У тебя из таблицы hashes будут забираться ключи с удалением, т.е. при вставке в url этого хэша уже не будет в hash

2024-11-12 19:13 UTC, mysosnovskaya requested changes

2024-11-12 19:13 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/v001_init.sql
> +    url TEXT NOT NULL,
Лучше не TEXT, а varchar с ограничением (пусть даже большим)

2024-11-12 19:13 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/v001_init.sql
> +    CONSTRAINT fk_url_hash FOREIGN KEY (hash) REFERENCES hashes (hash)
Посмотри коммент Паши :)

2024-11-12 19:13 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/v001_init.sql
Некритично, но букву V в миграции обычно пишут большой, а после версии два нижних подчеркивания делают (т.к. одно подчеркивание используется в качестве разделителя слов в остальной части названия миграции). V001__init.sql

2024-11-13 02:20 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/v001_init.sql
> +    url TEXT NOT NULL,
Хорошо

2024-11-13 02:20 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/v001_init.sql
Хорошо, поменяла

2024-11-13 02:31 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/v001_init.sql
> +    CONSTRAINT fk_url_hash FOREIGN KEY (hash) REFERENCES hashes (hash)
Как я поняла - нужно убрать CONSTRAINT

2024-11-13 22:09 UTC, mysosnovskaya approved these changes

2024-11-13 22:09 UTC, merged