BJS2-42715: Создание структуры БД
CorporationX/url_shortener_service pull request #573
Opened 2024-11-12 11:03 UTC by lowerKamaCase

https://faang-school.atlassian.net/browse/BJS2-42715

2024-11-12 11:37 UTC, lowerKamaCase commented
@mysosnovskaya 
![image](https://github.com/user-attachments/assets/16d66ef4-00b5-4423-889d-8a718f960d8b)
проект запускается.
но почему то схема не создается скриптом. почему так? пришлось руками создать.

2024-11-13 10:34 UTC, Varrankin commented on src/main/resources/db/changelog/changeset/V001.sql
> +    NO MINVALUE
как я знаю в  PostgreSQL 
    START WITH 1
    INCREMENT BY 1 
NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
    это значения по умолчанию, так что их нет смысла указывать если не используешь специфические значения

2024-11-14 03:48 UTC, lowerKamaCase commented on src/main/resources/db/changelog/changeset/V001.sql
> +    NO MINVALUE
оставил CACHE 1, остальные - да, идут по умолчанию.
спасибо!

2024-11-19 19:48 UTC, mysosnovskaya commented
> проект запускается. но почему то схема не создается скриптом. почему так? пришлось руками создать.

не поняла, по логам всё нормально, миграцию вижу, она успешно пройдена. А как ты проверяешь, что схема не создалась?

2024-11-19 19:49 UTC, mysosnovskaya requested changes

2024-11-19 19:49 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001.sql
> +    url TEXT NOT NULL,
Лучше не TEXT, а VARCHAR с ограничением на длину. Ограничение можно выбрать любое разумное, часто видела 4096

2024-11-21 10:50 UTC, lowerKamaCase commented
> > проект запускается. но почему то схема не создается скриптом. почему так? пришлось руками создать.
> 
> не поняла, по логам всё нормально, миграцию вижу, она успешно пройдена. А как ты проверяешь, что схема не создалась?

 смотрю в ДБивер, вижу, что схемы нет. Дальше запускаю проект. И он падает, потому что нет схемы. Затем я руками создаю схему, и все, проект нормально стартует. то есть первая строка creaete if not exists  как будто не работает

2024-11-21 10:51 UTC, lowerKamaCase commented on src/main/resources/db/changelog/changeset/V001.sql
> +    url TEXT NOT NULL,
поправил на
url VARCHAR(4096) NOT NULL,

2024-11-21 21:27 UTC, mysosnovskaya commented
> > > проект запускается. но почему то схема не создается скриптом. почему так? пришлось руками создать.
> > 
> > 
> > не поняла, по логам всё нормально, миграцию вижу, она успешно пройдена. А как ты проверяешь, что схема не создалась?
> 
> смотрю в ДБивер, вижу, что схемы нет. Дальше запускаю проект. И он падает, потому что нет схемы. Затем я руками создаю схему, и все, проект нормально стартует. то есть первая строка creaete if not exists как будто не работает

А! Т.е. именно со схемой проблема, а если она уже создана, то миграция корректно применяется?
Это всё потому, что liquibase сначала должен установить соединение с базой данных (и со схемой соответственно), затем создать там свои таблички databasechangelog и databasechangelog_lock и только после этого начать применять миграции. А у тебя в миграциях создание схемы стоит. Ну то есть порядок действий нарушен: правильно сначала создавать схему, а потом начинать выполнение миграций. В целом в миграциях никогда не прописывают создание схемы, т.к., во-первых, этим занимаются девопсы и предоставляют базу данных уже сразу с нужной схемой, а во-вторых для создания схемы нужен пользователь с расширенными правами, а его опасно подставлять в миграции.

2024-11-24 18:00 UTC, mysosnovskaya approved these changes

2024-11-24 18:00 UTC, merged