BJS2-42669 - URL Shortener
CorporationX/url_shortener_service pull request #594
Opened 2024-11-12 20:58 UTC by GusevVrn

Пока только часть тестов

2024-11-13 12:08 UTC, Silencemess1ah reviewed
В общем выглядит все оч круто, за оперативность 100 очков юникорнам, сделано на совесть, миграции через xml тоже прикольно не видел такого, вроде по логике все есть, единственное НО нужны думаю интеграционные тесты, как оно реально с потоками и прочим, как все будет думаю можно смело мержить, еще в некоторых классах по ПРу пробегись прям есть где нету отступа от класс нейма, в остальном ничего не заметил из стилевого, с меня лайк подписка!

2024-11-13 19:40 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +    }
Согласен, но я хочу полностью логику добить чтоб потом тесты писать.
Я заманался править тесты т.к. изменял логику довольно часто.
Может что забыл добавить или еще чего.

2024-11-13 19:40 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/service/cleaner/CleanerService.java
> +    @Async("urlThreadPool")
Смысл в том чтоб это в отдельном треде это все прогонять, с базой тут вообще никак не связано.

2024-11-13 19:40 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +    private static final String BASE62_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Вот по этой штуке не знаю, у нас же этот список принадлежит только к этому классу, выносить в параметры - так мы его менять не будем, делать доп класс параметров ну это уже перебор.

2024-11-13 20:52 UTC, segaTk commented on src/main/java/faang/school/urlshortenerservice/repository/hash/impl/FreeHashRepositoryImpl.java
> +            int end = Math.min(i + hashConfig.getInsertBatch(), hashes.size());
Чётко!

2024-11-13 21:04 UTC, segaTk commented on src/main/resources/db/changelog/changeset/V001__url_service_hash_table_script.xml
> +</databaseChangeLog>
Какая практика лучше? DDL или XML?

2024-11-13 23:13 UTC, mysosnovskaya requested changes
В следующий раз посмотрю ещё раз внимательно, так что возможно добавятся новые комментарии к уже написанному коду. Но пока вот что нашла) 
Ты, конечно, очень быстро всё реализовал!) И не могу сказать, что скорость сильно повлияла на качество, так что молодец!)

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +        Url url = findUrlInDatabaseByFullUrl(fullLink)
А не надо ли ещё в кэше поискать? Если это очень популярная ссылка, то она скорее всего есть в кэше, а из кэша достать гораздо быстрее, чем из базы данных

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +    private static final String BASE62_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Я бы не выносила, т.к. эта строка изменений не предполагает)

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +        return numbers.stream()
parallelStream может?)

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +    public List<String> encodeNumberListInBase62(List<Long> numbers) {
encodeNumbersToBase62 (List в названии не нужно, у тебя тут в целом любая коллекция могла бы быть)

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +        return encoded.reverse().toString();
А reverse зачем?) Кручу-верчу запутать хочу?)

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +      urlTtl: 3600
Можно комментом подписать, в чем это измеряется

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changelog-master.xml
> +<databaseChangeLog
Почему решил через xml сделать?)

2024-11-13 23:13 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/repository/hash/FreeHashRepositoryImplTest.java
> +/*
Почему закомментирован?

2024-11-13 23:13 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/repository/sequence/UniqueNumberRepositoryImplTest.java
> +        /*List<String> freeHashesInDataBase = hashService.getHashBatch();
?

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__url_service_hash_table_script.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Тут тоже вопрос - почему решил через xml?
На проектах обычно делают через sql, потому что они более читаемые, а переезд на другую базу данных крайне маловероятен) В xml довольно сложно воспринимается, особенно если много таблиц, колонок и прочего

2024-11-13 23:13 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__url_service_url_table_script.xml
> +            <column name="created_at" type="timestamptz"/>
not null? default?

2024-11-14 08:08 UTC, Lyroy-X commented on src/test/java/faang/school/urlshortenerservice/repository/sequence/UniqueNumberRepositoryImplTest.java
> +        /*List<String> freeHashesInDataBase = hashService.getHashBatch();
соглы

2024-11-14 20:49 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/V001__url_service_hash_table_script.xml
> +</databaseChangeLog>
Как обычно, как на проекте начали так и продолжать)

2024-11-14 20:49 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/entity/url/Url.java
> +    private Timestamp createdAt;
Потому что он в пакете sql, его и выбрал. 
Ну и в остальных сервисах у нас именно он был, посмотрел, поменял на LocalDateTime т.к. он оказывается более предпочтительней в новых приложениях.

2024-11-14 20:49 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/repository/hash/impl/FreeHashRepositoryImpl.java
> +        String sql = "DELETE FROM hash " +
Мне вот это не нравится, ладно у нас 1-2 метода, ты еще глазами можешь увидеть что там за запрос, а если у тебя метод на тысячной строчке, тебе надо переместиться на запрос, посмотреть его и  потом еще обратно вернуться не забыв что ты вообще делал.
По оптимизации, этот sql же где-то в пуле лежит, оттуда он и возьмется, сильно не проигрываем на этом, но читаемость кода выше.

2024-11-14 20:49 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +        Url url = findUrlInDatabaseByFullUrl(fullLink)
Мы по плану в кэш сохраняем только сам хэш(ключ), чтобы достать полную ссылку(значение) нам нужно знать ключ. Т.е. по такой логике мы еще должны в кэше хранить обратные значения ( полная ссылка - хэш), в целом звучит неплохо, я сам думал об этом но не в таком ключе, просто перерасход памяти кэша получается x2 от текущего.
Реализуем?

2024-11-14 20:49 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +        return encoded.reverse().toString();
Не знаю, так 100% работает, правил строку, убирал reverse и он начинает выдавать другой хэш, не совпадающий с правильным. Пусть будет так.

2024-11-14 20:49 UTC, GusevVrn commented on src/test/java/faang/school/urlshortenerservice/repository/hash/FreeHashRepositoryImplTest.java
> +/*
Не должен был попасть) Пропустил этот.

2024-11-14 20:49 UTC, GusevVrn commented on src/test/java/faang/school/urlshortenerservice/repository/sequence/UniqueNumberRepositoryImplTest.java
> +        /*List<String> freeHashesInDataBase = hashService.getHashBatch();
Да пумушта я все вертал и тут у меня окончательно сгорело что я в сотый раз тесты правлю.

2024-11-14 20:49 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/V001__url_service_hash_table_script.xml
> +<?xml version="1.0" encoding="UTF-8"?>
А я изучая liquibase пришел к выводу что тут наоборот xml реализация катируется.
Типо вот мы написали один скрипт, если хотим что-то поменять то делаем доп файл, а в xml конфигурации у тебя для каждой сущности отдельный файл и правишь все в своем файле.
Ну я попробовал, для закрепления, в след. сервисе сделаю через sql.

2024-11-14 20:51 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +        return numbers.stream()
Попозже попробую., когда до тестов дойду окончательно

2024-11-15 14:57 UTC, GusevVrn commented
Осталось юнит тест на urlService и интеграционный.
@mysosnovskaya меня терзают сомнения то что repository вообще надо тестить.

2024-11-15 19:45 UTC, mysosnovskaya requested changes
Тесты на репозитории лучше написать, т.к. у тебя там довольно сложные запросы. Можно использовать DataJpaTest для этого:
https://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-jpa-test

Также нужно ещё немного поработать над неймингом. Как всё поправишь, так будем мержить, комментариев по старому коду больше писать не буду (только по новому, если будет нужно))

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/config/cache/CacheProperties.java
> +    private int expirationUrl;
yearsToUrlExpiration
![image](https://github.com/user-attachments/assets/f81d1a44-bc8b-42da-85d4-54b118a46e1a)

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/hash/HashCache.java
> +    private final double COMMON_CAPACITY_PERCENTAGE;
Ну это же не константа, чтобы её так называть) Константа была бы static

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/config/cache/CacheProperties.java
> +    private int minLimitCapacity;
Так всё-таки это минимальное количество объектов в кэше? Называется так, а используется как проценты

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/hash/impl/FreeHashRepositoryImpl.java
> +        String sql = "DELETE FROM hash " +
Тут скорее идея была в том, что этот sql может занимать половину метода, и надо ли оно нам?) Но с твоими аргументами соглашусь, пусть так остается)

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +        Url url = findUrlInDatabaseByFullUrl(fullLink)
А, точно. Нет, второй кэш не нужен. Достаточно поиска в базе)

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__url_service_hash_table_script.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ну, у xml есть свои удобства, но неудобств как будто бы больше - они абсолютно нечитаемы)

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/controller/url/UrlController.java
> +    public String redirectShortLinkToFull(@PathVariable("hash") @NotBlank String hash) {
Лучше вернуть в хэдере Location, обычно так реализуют)

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +    public void saveRangeHashes(List<String> hashes) {
А зачем в названии range? Почему не просто saveHashes?

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/cleaner/CleanerService.java
> +    @Async("urlThreadPool")
Рекомендую ознакомиться
https://www.baeldung.com/spring-transactional-async-annotation

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +    public CompletableFuture<List<String>> generateBatchHash(int necessary) {
necessary это не существительное

2024-11-15 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/url/impl/UrlCacheRepositoryImpl.java
> +@Component
Компонент дублируется, в интерфейсе тоже есть)

2024-11-17 17:23 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/config/cache/CacheProperties.java
> +    private int minLimitCapacity;
Тут же количество определяем, а потом по формуле высчитываем процент

2024-11-17 17:27 UTC, GusevVrn commented
@mysosnovskaya осталось только с SpringJpaTest разобраться, там надо H2 накатить как-то правильно чтоб можно было отдельно тестировать репозиторий. 
В целом вроде накатил, но опять со схемой что-то не то. Пишут что достаточно в ресурсы sql файл со скриптами закинуть и он при запуске будет выполнять скрипт. Liquibase сам накатывает как и SpringBoot.

2024-11-17 19:56 UTC, mysosnovskaya reviewed
Про тест для репозитория увидела, но не поняла :) В ПРе этого теста нет. В чем ошибка?  Вообще это работает так: в main/resources есть файл schema.sql (обязательно называть именно так) и вот она в случае h2 должна накатываться автоматически. Конечно, схему лучше переместить в тестовые ресурсы, но это надо посмотреть, как правильно делать)

2024-11-17 19:56 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +    @Async("urlThreadPool")
А здесь опять Async + Transactional :)

2024-11-17 19:56 UTC, mysosnovskaya commented on src/test/resources/schema.sql
> +CREATE SCHEMASCHEMA IF NOT EXISTS URL;
SCHEMASCHEMA?

2024-11-17 20:35 UTC, GusevVrn commented on src/test/resources/schema.sql
> +CREATE SCHEMASCHEMA IF NOT EXISTS URL;
Да это я смотрел вообще хоть что-то делает с этим файлом или нет.
В логах create schema нету. Только liquibase ругается что schema not exists.

Добавил h2, схему не создает, пытался так в конфигах прописать
```
    url: jdbc:h2:mem:db;SCHEMA=URL;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:db;CREATE SCHEMA URL;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:db;CREATE SCHEMA URL;SET SCHEMA URL; DB_CLOSE_DELAY=-1
```
плюсом он ломает интеграционный, видимо этот h2 начинает использоваться как дефолтная бд

2024-11-18 19:31 UTC, mysosnovskaya approved these changes
Я готова мержить. Поправь последний коммент и если не собираешься больше менять тесты, то можешь самостоятельно смержить)

2024-11-18 19:31 UTC, mysosnovskaya commented on build.gradle.kts
> +    //testImplementation("com.h2database:h2")
Либо раскомментировать, либо удалить

2024-11-18 20:27 UTC, merged

2024-11-18 21:04 UTC, Silencemess1ah commented
Поздравляю🎉🎊