Unicorn master stream6 varya feature bjs2 42666
CorporationX/url_shortener_service pull request #597
Opened 2024-11-12 21:15 UTC by StepnovaVarvara

2024-11-13 08:01 UTC, GusevVrn reviewed
Ок, только один момент поправить

2024-11-13 08:01 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    @OneToOne
ты же связь убрала?

2024-11-13 17:06 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    @OneToOne
Да, убрала. Просто я твой коммент увидела уже после того как эту задачку сделала)

2024-11-13 22:22 UTC, mysosnovskaya requested changes
Когда смержишь задачу про репозиторий, то не забудь обновить эту ветку так, чтобы в ней не было лишних классов, а был бы только Base62Encoder и тестовый класс для него

2024-11-13 22:22 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        return numbers.stream()
Может распараллелить?)

2024-11-13 22:22 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +                .collect(Collectors.toList());
Просто toList()

2024-11-13 22:22 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        log.info("start encodeNumber with number - {}", number);
А потом в логах будет 10000 вот таких вот записей (и потом ещё 10000 на финиш)? Если хочется лог, то можно его добавить в метод encode (в начало и конец) с логированием чисел от какого и до какого будет происходить генерация. А отсюда точно удалить, а то все логи этим заспамим

2024-11-13 22:22 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/service/Base62EncoderTest.java
> +    @InjectMocks
А эта аннотация зачем? В Base62Encoder никаких моков внедрять не нужно)

2024-11-13 22:22 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/service/Base62EncoderTest.java
> +    public void whenEncodeThenReturnListHash() {
Какой-нибудь посложнее бы тест, с числами хотя бы больше 100, а лучше больше 100000

2024-11-14 02:32 UTC, StepnovaVarvara commented on src/test/java/faang/school/urlshortenerservice/service/Base62EncoderTest.java
> +    public void whenEncodeThenReturnListHash() {
щас все сделаем!))

2024-11-14 02:38 UTC, StepnovaVarvara commented on src/test/java/faang/school/urlshortenerservice/service/Base62EncoderTest.java
> +    @InjectMocks
да, но без нее надо писать new...

2024-11-14 02:50 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +                .collect(Collectors.toList());
да, так проще

2024-11-14 02:52 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        log.info("start encodeNumber with number - {}", number);
блин, жеееесть какая я лошара!

2024-11-14 03:05 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        return numbers.stream()
Такс, в части распараллеливания - я щас сижу над задачкой с хешгенератором, где будет метод, который из 10 потоков дергает этот метод, чтобы для одного большого листа чисел создать хешей. Добавлять еще и сюда потоки - мне страшно!)) Еще мне тяжело понять на скок это разумно при условии, что потоки на эти две задачки мы будем брать из одного пула... Короче, мне тут оч сложно сказать ускорит это весь процесс или нет

2024-11-14 17:36 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        return numbers.stream()
Обсудили на дейли, здесь тогда распараллеливание не нужно

2024-11-14 17:37 UTC, merged