Feature bjs2 42697
CorporationX/url_shortener_service pull request #612
Opened 2024-11-13 19:42 UTC by Silencemess1ah

- added previous PR's to make this task possible
- added HashGenerator class + IT, ThreadPoolTaskExecutor, refactored some logic with save and custom Policies

2024-11-15 03:25 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/generator/hash/HashGenerator.java
> +            String threadName = Thread.currentThread().getName();
Короче, либо я что-то не понимаю, либо не знаю... По моей логике мы сюда должны зайти не мейн потоком и метод, который base62Encoder.encode(), должен выполнятся сразу множеством потоков, чтобы ускорить весь процесс. А щас получается, что над этой задачкой у нас трудится только один не мейн поток. Короче, будет возможность, дерни меня и объясни

2024-11-18 20:49 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/generator/hash/HashGenerator.java
> +            String threadName = Thread.currentThread().getName();
Короче идея чтоб не generateBatch выполнялся толпой, а encode возвращал future и потом пачку этих Future собираем и соединяем в общий List<String> хэшей

2024-11-18 20:49 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/generator/hash/HashGenerator.java
> +            String threadName = Thread.currentThread().getName();
попробую переделать на такой вариант

2024-11-19 20:10 UTC, mysosnovskaya requested changes

2024-11-19 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/hash/CustomHashRepositoryImpl.java
> +    @Transactional
Зачем?)

2024-11-19 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/hash/CustomHashRepositoryImpl.java
> +    public void saveAllCustom(List<Hash> hashes) {
Лучше не Custom, а Batch

2024-11-19 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +    private List<List<Long>> partitionList(List<Long> initialList, int numberOfPartitions) {
Для этого уже есть готовые решения, например у apache commons

2024-11-19 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +        List<List<Long>> partitions = partitionList(numbers, threadsAmount);
Всё это распараллеливание это не ответственность энкодера. Он просто превращает числа в хэши. А вот вызывать его можно как угодно - можно хоть список из одного числа ему передать, а можно снаружи разбить на подсписки и вызывать для каждого подсписка свой encode. А тут нам сам encode навязывает асинхронное выполнение, хотя это даже не всегда может быть нужно

2024-11-19 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/config/executor/rejection/CustomCallerRunsPolicy.java
> +        log.info("We are experiencing high server loads due to the influx of visitors. Please remain calm."
В логах это увидит только разработчик и только если решит туда заглянуть)

2024-11-19 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/config/executor/rejection/CustomCallerRunsPolicy.java
> +public class CustomCallerRunsPolicy implements RejectedExecutionHandler {
Нам бы вообще стараться не допускать таких ситуаций) Но мне нравится, что ты это нашел и добавил к себе 👍

2024-11-19 20:57 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/repository/hash/CustomHashRepositoryImpl.java
> +    @Transactional
Ты меня в ступор ввела, а почему нет? Если у нас куча запросов из generateBatch() летит сюда, чтобы каждый записывал что нужно и не было перезаписей между потоками , идея по крайней мере такая, излишне для такой логики?

2024-11-19 20:59 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/config/executor/rejection/CustomCallerRunsPolicy.java
> +        log.info("We are experiencing high server loads due to the influx of visitors. Please remain calm."
Забыл про инфо,  тест писал посмотреть если задач больше 200 сотен прилетает что отработает логика

2024-11-19 21:15 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +        List<List<Long>> partitions = partitionList(numbers, threadsAmount);
Тобишь логика у нас следующая, мы до того как будет дергать encode метод/ы  (его оставляем как был до этого) просто перегоняет из чисел в хэши,  дробим uniqueNumbers на предположим как я здесь сделал на кол-во активных потоков, передаем этот sublist потоку и пускай с ним идет делает encode? Потом собираем в кучу Хэши которые они наЭнкодили и сохраняем в базу ? Так это выглядеть будет? Я просто к тому что я просто логику всю вынес сюда а надо на уровне HashGenerator было это все делать я верно мыслю?

2024-11-19 21:48 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java
> +        List<List<Long>> partitions = partitionList(numbers, threadsAmount);
В общем отрефакторил в другую сторону баррикады + учел про ListUtils.partition от apache commons

2024-11-20 17:54 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/hash/CustomHashRepositoryImpl.java
> +    @Transactional
Но у тебя же один запрос к базе данных в этом методе? Как ему транзакция поможет?)

2024-11-20 18:03 UTC, mysosnovskaya reviewed
Нужно с filling.set разобраться, в остальном всё ок)
А ещё обрати внимание, что у тебя ошибка компиляции (сборка в github actions не прошла)

2024-11-20 18:03 UTC, mysosnovskaya commented on src/test/java/faang/school/urlshortenerservice/cache/hash/HashCacheIntegrationTest.java
> +        Thread.sleep(1000);
Секунды, наверное, многовато) 
Вообще в тестах стараются избегать таких sleep (они сильно удлиняют тесты). Можно было бы в цикле while ходить в течение секунды и если за секунду до 200 так и не дошли, то сделать fail (тест упадет). Текущую реализацию можешь оставить, это я скорее на будущее

2024-11-21 07:05 UTC, Silencemess1ah commented on src/main/java/faang/school/urlshortenerservice/cache/hash/HashCache.java
> +                isFilling.set(false);
Сделал через try-catch-finnaly чтобы сбросить isFilling в false в случае проблем

2024-11-21 21:37 UTC, mysosnovskaya approved these changes

2024-11-21 21:37 UTC, merged