Url shortener common PR bjs2 43035 bjs2 43027 bjs2 43029 bjs2 43032 bjs2 43030 bjs2 43031 bjs2 43033 bjs2 43034 bjs2 43036
CorporationX/url_shortener_service pull request #630
Opened 2024-11-14 17:05 UTC by sultan-inked

2024-11-14 17:12 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/aspect/redis/IsRedisConnectedAspect.java
> +}
Требуется что бы отловить иключение в случае отсутствия соединения с редисом, дабы основная транзакция не падала.
В рамках повышения отказоустойчивости, а то если редис вдруг откажет то и в БД нельзя будет сохранить.
Но вешаю только на сохранение и получение данных из кеша, но на удаление нельзя, а то получится так что в БД удалили а в редисе нет.
Использую на методах этого класса:
https://github.com/CorporationX/url_shortener_service/pull/604/files#diff-ba20c548a72e329352ca283cd0f523daac372bb89cbc2add3d47d6a310c247b0

2024-11-14 17:15 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +}
Использовал только AtomicBoolean, потому что он пропускает только первый поток который заметил флаг.
Проверял, на скрине 5 потоков, еще проверля на 5000 запросов без задержек xерез постман, всегда обновляет только один поток:
![image](https://github.com/user-attachments/assets/d0edf626-6631-42ac-bf0b-0c7c1e14ec84)

2024-11-15 09:52 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +    }
Вариант с тем что бы проверять сначала флаг не работает, потому что первый поток который проверил сразу его менят, без проверки второго условия.
Потом думал использовать BlockingLinkedDeque, потому что у него проверка размеа O(1), но он блокирующий.
В итоге использол AtimicInteger, без синэронизации с очередью, небольшие отклонения не критичны, счетчик и размер очереди никогда не опустится до нуля, и просто обновление будет иногда чуть раньше или чуть позже, мне показалось плюсы перевешивают один небольшой недостаток:
Плюсы: не блокирующая очередь с хорошей обработкой больших потоков на вставку и получение, проверка размера за одно действие
Минусы: небольшой рассинхрон в обновлении очереди

2024-11-15 09:54 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashGenerator.java
> +}
Добавил проверку размера хешей в БД, что бы не генерить много лишенго

2024-11-15 15:28 UTC, 20cognosce requested changes

2024-11-15 15:28 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlCleanerService.java
> +        urlCacheRepository.deleteAll(hashes);
Добавь пояснений имена или комментом, что мы удаляем ссылки, но получаем ВЫСВОБОЖДЕННЫЕ хэши, и пересохраняет их снова

2024-11-15 15:28 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashGenerator.java
> +}
2L - это называется magic number
В константу вынеси или коэффициент объяви 0.75 например, не понятно, что это за условие в if ()

2024-11-15 15:28 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +            """)
Не хочешь локать url? Что если в последнюю секунду её жизни будет наплыв миллиона пользователей

2024-11-15 15:28 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/hash/HashJdbcRepository.java
> +        });
Зачем? Докажи мне это бенчмарком, что это значительно лучше, чем saveAll

2024-11-15 15:28 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/hash/HashJdbcRepository.java
> +            List<String> batch = hashes.subList(fromIndex, toIndex);
Это к тому же выглядит устрашающе

2024-11-15 15:52 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/aspect/redis/IsRedisConnectedAspect.java
> +}
Ты просто в задаче с хеш тегами писал убрать try catch везде, думал так скрыть

2024-11-15 16:27 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public String createHashUrl(@RequestBody @Valid UrlRequestDto urlDto, BindingResult bindingResult) {
Да, переделаю, но это и есть код 300:
<img width="771" alt="Снимок экрана 2024-11-15 в 21 26 31" src="https://github.com/user-attachments/assets/3934db3e-558e-43ff-8b47-1e66a4d5dea9">

2024-11-16 09:21 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
После отключения то что было во внутреннем кеше сгорают, и при добавлении после вскючения надо еще нагенерить для восполнения

2024-11-16 09:27 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        hashesSize.set(newHashes.size());
Дело не в потоко-безопасности, а в том что проверка размера в ConcurrentLinkedDeque О(n), в BlockingLinkedDeque проверка размера O(1), но это блокирующая очередь, почему в таком случае нелься использовать одельную переменную, жертвую синхронностью но получая не блокирующую очередь и проверку в одно действие?
Единственный минус который я вижу это обновление очереди может быть немного раньше или позже,  могу ошибаться, возможно что не понимаю, но почему нет? Что может пойти не так, если у очереди есть нижняя граница в 20 проценов?

2024-11-16 09:44 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +            """)
Если удалять без подзапроса. то можно не делать явную блокировку?
```sql
DELETE FROM url
WHERE created_at < :date
RETURNING hash
```

2024-11-16 10:07 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/util/uri/UriBuilder.java
> +public class UriBuilder {
Ты об этом? Или что то другое?
```java
public String response(String hash) {
    return ServletUriComponentsBuilder
            .fromCurrentContextPath()
            .path("/{hash}")
            .buildAndExpand(hash)
            .toUriString();
}
```

2024-11-16 11:29 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
Генерация выполняется асинхронно

2024-11-16 11:33 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +    }
<img width="818" alt="Снимок экрана 2024-11-16 в 16 33 14" src="https://github.com/user-attachments/assets/b3585f3e-7101-44fa-a2d6-618ee640ddaf">

2024-11-16 11:36 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +    }
Это самое компактное из того что нашел, есть более простой способ получения байтов из числа, но в этом случае итоговый хеш получается с нулями, что не гарантирует уникальность:
```java
private byte[] longToBytes(long number) {  
    ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES);  
    buffer.putLong(number);  
    return buffer.array();  
}
```

```
expected: 
  ["93r", "97z", "9C7", "9GF", "9KN", "9OV", "9Sd", "9Wl", "9at", "9f1", "9j9"]
 but was: 
  ["0000001Ie", "0000001If", "0000001Ig", "0000001Ih", "0000001Ii", "0000001Ij", "0000001Ik", "0000001Il", "0000001Im", "0000001In", "0000001Io"]
```

2024-11-17 12:44 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/repository/hash/HashJdbcRepository.java
> +        });
И батч для хибера включен:
<img width="644" alt="Снимок экрана 2024-11-17 в 17 44 06" src="https://github.com/user-attachments/assets/3df1e5cb-e5e7-4948-8a4f-3ab68c3fa313">

2024-11-17 12:55 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/repository/hash/HashJdbcRepository.java
> +            List<String> batch = hashes.subList(fromIndex, toIndex);
Что именно тебя пугает? subList?

2024-11-17 20:43 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/repository/hash/HashJdbcRepository.java
> +        });
Убрал Jdbc

2024-11-18 10:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/uri/UriBuilder.java
> +public class UriBuilder {
Другие тоже есть

2024-11-18 10:32 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +            """)
Можно

2024-11-18 10:33 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +    }
В данной задаче нет никакой разницы, o(n) или o(1)

2024-11-18 10:53 UTC, 20cognosce requested changes

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/cache/UrlCacheRepository.java
> +            return null;
Что это за null

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
ты так и не ответил на вопрос, почему нельзя взять из базы готовые кэши при старте, а обязательно делать генерацию

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +    private final AtomicInteger hashesSize = new AtomicInteger(0);
Этого быть не должно, нет разницы почти никакой в данной задаче

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        }
Можно тогда сначала выставлять флаг всегда и внутри делать вторую проверку на размер и затем флаг отпускать

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashGenerator.java
> +    private long maxDbHashesSize;
max_db_hashes_size?
Если у нас строк меньше максимума, мы генерим новые, пока не достигнем максимума?

Это не максимум тогда, ты вводишь в заблуждение таким неймингом

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +        ByteArrayOutputStream bos = new ByteArrayOutputStream();
Обязательно открывать поток вывода? 
Это тормозить будет, так не пойдет

Тебе нужно из уникального числа просто сделать массив байт и скормить его шифратору

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +    }
А хэш нельзя обрезать без нулей? И выставить проверку на размер ненулевых символов

Если не получится нормально это сделать - возвращай свою реализацию с остатком от деления

2024-11-18 10:53 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +            number >>>= 8;
Это на сколько ты умножаешь каждый байт? Тебе не кажется, что ты так вылезти можешь за границы 
Не нравится мне это

2024-11-18 16:14 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
В таком случае можно вообще не генерить.
Мы всегде генерим когда берем из бд, какая разница, приложение только запустилось и мы берем из БД и асинхронно генерим на будущее новые, или во время работы берем из БД и так же асинхронно генерим новые точно так же на будущее? Не понимаю что имнно тебя смущает, я и так беру из БД, и запускаю генерацию что бы восполнить то что взял, что бы в следующий раз точно так же взять и возполнить, если при старте просто возьму, то может случиться так что в БД нет хешей, потому что я при старте просто взял, но почему то не восполнил.

2024-11-18 16:26 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/repository/cache/UrlCacheRepository.java
> +            return null;
В случае отсутствия соединения с редисом, что бы не упасть с исключением, отлавливается исключение, и что бы приложение работало дальше этот метод должен что то вернуть, Редис, если не находит запись то возвращает null, вот, поэтому тут он и прописан

2024-11-18 16:58 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +    }
Сделал просто обрезание, вроде так не будет повторений

2024-11-18 17:03 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +        return buffer.array();
Сделал получение байтов из уникального числа, которой генерируется, например, в это: "0000001Ie", и как ты подсказал, просто обрезается "1le".

2024-11-20 18:16 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/cache/UrlCacheRepository.java
> +            return null;
Я понял, зачем ты это сделал
И все равно это не делает возврат null допустимым решением, переделывай на опшинал или еще как-нибудь это обрабатывай

2024-11-20 18:30 UTC, 20cognosce approved these changes

2024-11-20 18:30 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/encode/Base62Encoder.java
> +    }
Супер
Только отрезание нулей мне не нравится, ты гарантируешь одинаковую длину всех хэшей?

2024-11-20 18:30 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +            isUpdating.set(false);
isUpdating - не лучшее наименование
генерация еще будет происходить когда уже флаг стоит в false

Этот флаг именно на асинхронное наполнение кэша

2024-11-20 18:30 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +            hashGenerator.generate();
Тут кстати не сразу заметно, что это асинхронный запрос
Я бы два экзекьютора в этом классе завёл

2024-11-20 18:30 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
Да, это всё так
Но фишка в том, что взять из базы - первый приоритет
А генерация - второй

Потому что взять из базы быстрее, и если все инстансы будут в первую очередь идти в базу за готовыми хэшами это позволит не ждать долгого старта, что даёт быстрый скейлинг количества реплик нашего сервиса (масштабирование)

2024-11-21 05:27 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +            isUpdating.set(false);
Флаг на обновление внутреннего кеша, а не на генерацию, внутренний кеш наполился и флаг переключили, он не должен зависить от асинхронной генерации, если генерация еще не закончилась а кеш уже пуст, то получается по твоей логике надо ждать асинхронной генерации что бы заполнить кеш? Зачем тогда делать генерацию асинхронно если заполнение кеша его будет ждать?
Я тупой, объясни на пальцах пожалуйста)

2024-11-21 05:33 UTC, sultan-inked commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
Не понимаю, как асинхронная генерация влияет на то что мы идем в БД и берем готовые хеши.
Ты пишешь, надо брать из базы и не ждать генерации, в коде происходит запуска потока который в фоне генерит хеши, и сразу не дожидаясь окончания генерации идет в БД для получения хешей, где здесь противоречие?
Возможно я не понимаю чего то, объясни пожалуйста)

2024-11-25 16:31 UTC, 20cognosce approved these changes

2024-11-25 16:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +        updateHashes();
Всё так, но когда идет генерация - флаг должен стоять, чтобы все знали, что уже наполняем базу
И генерация отвечает за то, чтобы тебе всегда было, что из базы брать, это тоже очень важно

Если генерация не работает - мы сломаемся рано или поздно

2024-11-25 16:35 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/util/HashCache.java
> +            isUpdating.set(false);
Я так и написал, что этот флаг говорит, что сейчас уже есть поток, который наполняет наш кэш данными из базы
Ты назвал его isUpdating - апдейтинг чего? Не понятно, поэтому я и попросил конкретику

На генерацию флаг не нужен, так как она триггерится трешхолдом на локальном кэше, и если мы isCacheUpdating из true перевели в false, значит кэш заполнен хэшами

Мысль была, что если генерация не закончилась, и кэш опустел, что уже понадобилась новая генерация.
Наверно, это практически невозможно.

Нормально всё с кодом короче.

2024-11-25 16:37 UTC, merged