URL Shortener - Full
CorporationX/url_shortener_service pull request #632
Opened 2024-11-14 20:55 UTC by amilosh

2024-11-15 15:16 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +    }
Вот так не работает
private final Queue<String> cache = new ArrayBlockingQueue<>(cacheCapacity);
во время оздания cache спринг ещё не успел проинициализровать cacheCapacity
  вынес это в postConstruct

пробовал через консруктор, но чисто визуально так больше нравится

2024-11-15 15:26 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +        cache.addAll(hashesFromDb);
Смотрел сможем ли когда-нибудь выйти за капасити и получить ошибку. Нет. Потому что batchSize для заполнения 800, а это метод выполнится только когда cache.size() строго меньше 200.

2024-11-15 15:28 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +        if (isFillingUp.compareAndSet(false, true) && cache.size() < threshold) {
cache.size() < threshold - в задаче указано, что нужно граничное значение в пройентах держать (20%)
но это лишнее, мы и так задаем в пропертях cache-size = 1000, то сразу же задаи и threashold 200
чтобы в коде поятонно не высчитывать 20% от 1000

2024-11-15 16:17 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +}
ExecutorService - java core, а ExecutorService - для спринга аи работы с Async.
В заданиях указано, чтобы мы и тот и тот заипользоваали.
Но если бы не было так указано, то здесь
```
private void fillUpCacheIfNeeded() {
        if (isFillingUp.compareAndSet(false, true) && cache.size() < threshold) {
            fillUpCacheExecutorService.execute(() -> {
                ...
            });
        }
    }
```
можно было бы и hashesGeneratorTaskExecutor использовать? (дргое название только)

я вот сделал, что для каждой функцинальности свой executor
а когда мы делаем один общий executor и используем его в различных местах (в `@ssync` и execute()) - это нормальный подход?

2024-11-15 16:18 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    private int threadPoolSize;
я задал размер один, потому что из-за блокировки isFillingUp.compareAndSet(false, true) один поток будет выполняться всегда

2024-11-15 16:20 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +    }
моя логика тут такая
генерю 1000 + 800 хэшей, сохраняю в БД
потом вытягиваю 1000 и запихиваю в cache, чтобы 800 осталось в БД, и не прииходилось генерить а можно было бы сразу взять из БД
и весь метод - не асинхронный, чтобы бин создался и в нё точно лежало 1000 хэшей в cache

2024-11-15 16:22 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +    }
А здесь такая логика. Я беру 800 записей из БД. Сразу добавляю в cache.
А потом асинхронно оправляю дозаполлнять таблицуу и отпускаю флаг.

2024-11-15 16:46 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java
> +}
Гуглил что редис предлагает.
Если мы ключ и значение в виде стринги туда отправляем, то они для этого кейса сделали специальнй темплейт StringRedisTemplate.

2024-11-15 16:47 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/exception/handler/AppExceptionHandler.java
> +    }
В задании сказано сделать обработчик всех ошибок.
Наверное нужно ещё просто Exception.class добавить обработчик?

2024-11-15 16:48 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/CleanHashesService.java
> +}
Для клина хэшей хотел использовать один из сервисов, но так и сяк сслка друг на друга получается. Поэтому я сделал отдельный, который никому не мешает.

2024-11-15 20:19 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/repository/redis/UrlCacheRepository.java
> +        stringRedisTemplate.opsForValue().set(hash, url, 7, TimeUnit.DAYS);
Я решил, чо буду одну неделю хранить.

2024-11-17 15:10 UTC, 20cognosce requested changes
Без тестов задачи не принимаются

2024-11-17 15:10 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    }
![image](https://github.com/user-attachments/assets/61ed6f0c-7ce9-4755-9d0c-fd86b0805ed2)
?

2024-11-17 15:10 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +}
Нет, под каждую задачу свой отдельный пул

2024-11-17 15:10 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    public TaskExecutor hashesGeneratorTaskExecutor() {
Ты его вообще где-то используешь? Не могу найти

2024-11-17 15:10 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    private static final String GET_URL_PATH = "/url/";
Почему не в отдельном классе со всеми константами

2024-11-18 21:10 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +}
Вернул saveAll()

2024-11-18 21:11 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +        if (isFillingUp.compareAndSet(false, true) && cache.size() < threshold) {
Прав. Я не доглядел этот момент.

2024-11-18 21:15 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +        if (isFillingUp.compareAndSet(false, true) && cache.size() < threshold) {
Вернул обратно как было.

2024-11-18 21:23 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +    }
Там не будет кучи вободных, там будет только то количество, которое нужно для нормальной работ первого инстанса.

2024-11-18 21:24 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +    }
Поменял на конструктор.

2024-11-18 21:33 UTC, amilosh commented on src/main/resources/db/changelog/changeset/url_shortener_V001__initial.sql
> +    hash       VARCHAR(6)          PRIMARY KEY,
я специально сделал, чтобы после not null шел)
поправил

2024-11-18 21:42 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/repository/postgres/hash/IHashRepository.java
> +public interface IHashRepository {
удалил

2024-11-18 21:56 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/CleanHashesService.java
> +        hashService.saveAll(cleanedHashes);
Замечание резонное. Отписал в чате.

2024-11-18 22:02 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +    private final HashRepository hashRepository;
из IHashRepository

2024-11-18 22:02 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +        hashRepository.saveBatch(hashes);
я постманом проверял, всё работает

2024-11-18 22:02 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/repository/postgres/hash/HashRepositoryImpl.java
> +        );
удалил

2024-11-18 22:17 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashGenerator.java
> +        List<Long> uniqueNumbers = hashRepository.getUniqueNumbers(batchSize);
если в hashService.saveAll(hashes) что-то упадет, то всё равно в сиквенс значения не вернутся, то есть тут вообще транзакция ничему не поможет

2024-11-18 22:17 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashGenerator.java
> +        List<Long> uniqueNumbers = hashRepository.getUniqueNumbers(batchSize);
убрал

2024-11-18 22:23 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +        cache = new ArrayBlockingQueue<>(cacheCapacity);
взял ConcurrentLinkedDeque

2024-11-18 22:26 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    }
буду знать

2024-11-18 22:27 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    private static final String GET_URL_PATH = "/url/";
вынес в ямл

2024-11-18 22:28 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    public TaskExecutor hashesGeneratorTaskExecutor() {
тут
[    @Async("hashesGeneratorTaskExecutor")
    public void generateBatchOfHashesAsync(int batchSize) {
        generateBatchOfHashes(batchSize);
    }](url)

2024-11-18 22:29 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/config/properties/GeneralProperties.java
> +}
вынес в ямл

2024-11-21 09:25 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +    }
Вот эту взял
https://github.com/unbroken-dome/base62

2024-11-22 21:00 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +                .expirationTime(LocalDateTime.now().plusMonths(lifeTime))
И тут добавил.
Пока сделал по количетву месяцей из проперти. Если нужно будет с точностью до дней - то в след. изменении росто добавить plusDays()

2024-11-22 21:00 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/repository/postgres/url/UrlRepository.java
> +            WHERE hash IN (SELECT hash FROM url WHERE expiration_time > CURRENT_TIMESTAMP FOR UPDATE)
И здесь тогда вот удобно удалять, как ты посоветовал.

2024-11-23 20:36 UTC, 20cognosce requested changes

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/postgres/url/UrlRepository.java
> +            WHERE hash IN (SELECT hash FROM url WHERE expiration_time > CURRENT_TIMESTAMP FOR UPDATE)
Не в ту сторону условие
Дата экспирации - 12:30
Сейчас - 12:40

Условие удаления - дата экспирации < сейчас

Удаляешь еще живые ссылки

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/hash/HashService.java
> +        hashRepository.saveAll(entities);
Он итак транзакционный, на весь метод не обязательно вешать

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    public TaskExecutor hashesGeneratorTaskExecutor() {
Снова поднимается вопрос, чем тебе не подходит singleThreadPoolExecutor

У тебя всегда ровно один асинхронный поток занимается наполнением базы

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/thread/ExecutorsConfig.java
> +    public TaskExecutor hashesGeneratorTaskExecutor() {
Один на наполнение базы и один на чтение заготовленных хэшей из базы

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    private String getHashUrl;
не удачное наименование переменной

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    private Integer lifeTime;
добавь, что это к ссылке относится

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    private Integer lifeTime;
И почему Integer? Используй классы из java.time

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +                .expirationTime(LocalDateTime.now().plusMonths(lifeTime))
1. Лучше это в маппере / билдере как отдельном классе
2. Длительной жизни ссылки - это не число, это класс из java.time
На крайняк передавай свой собственный класс, собирающийся из пропертей, с полями: месяцев, дней, секунд

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +    }
Тут не пойми что происходит
Это надо отрефакторить

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java
> +    }
Магические числа повсюду...

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/HashGenerator.java
> +    @Transactional
Ты же лочишь строки в базе итак

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +            @Value("${app.hashes-generation.initial-filling-size:250}") int initialFillingSize,
Откуда берутся значения с именами переменных?
:1000
:200
?

2024-11-23 20:36 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/util/HashCache.java
> +        List<String> hashesFromDb;
Может лучше внутри блоков if делать cache.addAll()

2024-11-26 16:17 UTC, 20cognosce approved these changes

2024-11-26 16:17 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/properties/UrlLifeTimeConfig.java
> +@Component
Конфигурация итак бин

2024-11-26 16:17 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/postgres/url/UrlRepository.java
> +            RETURNING hash
Форматирование

2024-11-26 16:17 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +                .plusHours(lifeTime.getHours());
null принимает нормально?

2024-11-26 16:17 UTC, 20cognosce commented on src/main/resources/application.yaml
> +  path-with-hashed-url: ${app.base-url}/url/
with-hashed-url - это что значит? не понятно

2024-11-26 16:17 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    threadNamePrefix: "HashesGenerator-"
Не используется нигде же

2024-11-26 16:18 UTC, merged

2024-11-30 10:58 UTC, amilosh commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +                .plusHours(lifeTime.getHours());
А там не будет null.
В UrlLifeTimeConfig
  int months

если в application.yaml не будет засетано проперти, то палик не поднимется