Unicorn master stream6 varya feature bjs2 42658
CorporationX/url_shortener_service pull request #643
Opened 2024-11-16 03:44 UTC by StepnovaVarvara

2024-11-18 19:57 UTC, mysosnovskaya requested changes

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    @Transactional
Рекомендую ознакомиться
https://www.baeldung.com/spring-transactional-async-annotation

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        log.info("start getHash");
Это не надо =)

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            log.info("percentage of cache filling: {}", getFullnessCache());
Тоже не надо) Запросы на хэш будут поступать сотнями (если не тысячами) в секунду, логи при каждом вызове метода в этом случае бесполезны. Логи должны быть только в тех местах, где они будут редкими и поэтому говорящими

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                hashGenerator.generateBatch();
generateBatch у тебя запускается асинхронно благодаря аннотации Async, а выше getHashesBatch запускается асинхронно с помощью CompletableFuture. Нельзя ли один общий подход сдлать?

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        String hash = Objects.requireNonNull(hashesCache.poll()).getHash();
А если в кэше пусто, то пользователь получит ошибку? А пользователь ведь не виноват. Он очень расстроится и будет грустить) Нам нельзя пользователя огорчать, поэтому ошибки тоже кидать нужно только по делу. 
Вообще говоря при нашей архитектуре у нас не можем быть ситуации, когда в кэше ничего нет, при хорошо подобранных значениях параметров. Но если хочется обработать эту ситуацию, то можешь хотя бы в цикле while ждать, пока в кэше ничего не появится. Генерация же уже запущена. Но это прям совсем костыль, который при больших нагрузках не поможет вообще никак) Так что нам просто нельзя допускать такой ситуации)

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        return hashesCache.size() * ONE_HUNDRED / cacheProperties.getCapacity();
ONE_HUNDRED / cacheProperties.getCapacity(); всегда имеет одинаковое значение, можно его заранее рассчитать

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +    @Transactional
Аналогично

2024-11-18 19:57 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        hashRepository.saveAllHashesBatched(hashes);
У тебя ниже вся эта же логика, только распараллеленная. А здесь придется ждать сильно дольше. А это будет тормозить запуск приложения. Почему здесь без распараллеливания тогда?)

2024-11-19 17:02 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    @Transactional
Ага

2024-11-19 17:03 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        log.info("start getHash");
убрала

2024-11-19 17:03 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            log.info("percentage of cache filling: {}", getFullnessCache());
убрала

2024-11-19 17:06 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        String hash = Objects.requireNonNull(hashesCache.poll()).getHash();
ну по сути она у нас и не может возникнуть

2024-11-19 17:08 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +    @Transactional
убрала

2024-11-19 17:12 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        return hashesCache.size() * ONE_HUNDRED / cacheProperties.getCapacity();
сделала в отдельную переменную

2024-11-19 17:20 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        hashRepository.saveAllHashesBatched(hashes);
На сколько я поняла - методы, которые мы вызываем в конструкторе не могут быть помечены аннотацией @Async. Именно поэтому я сделала отдельный метод без этой аннотации

2024-11-19 17:29 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                hashGenerator.generateBatch();
Не совсем понимаю, что значит общий подход?! Имеется ввиду и там и там делать CompletableFuture или Async?

2024-11-19 18:03 UTC, StepnovaVarvara commented
Маша, я в метод generateBatch() еще добавила изменения из другой задачки по твоим замечаниям. Не нужно было разбивать задачу на подзадачки, жестко путаюсь уже в них!!

2024-11-19 19:54 UTC, mysosnovskaya approved these changes
Можешь поправить и смержить самостоятельно)

2024-11-19 19:54 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        int capacityFactor = ONE_HUNDRED / cacheProperties.getCapacity();
Вообще я имела в виду, что это можно сделать полем класса. Один раз посчитали при инициализации класса и потом всегда пользуемся. А так каждый раз значение этой переменной считать нужно)

2024-11-19 19:54 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        CompletableFuture<List<Hash>> combinedFuture = CompletableFuture.completedFuture(new ArrayList<>());
Зачем здесь инициализация, если ниже ты эту переменную заново инициализируешь?
А вообще со стримами хорошо получилось на мой взгляд 👍

2024-11-19 19:55 UTC, mysosnovskaya commented
> Маша, я в метод generateBatch() еще добавила изменения из другой задачки по твоим замечаниям. Не нужно было разбивать задачу на подзадачки, жестко путаюсь уже в них!!

Это ты про BJS2-4266? Тогда закрой соответствующий ей ПР (не мердж, а просто close) и я закрою ту задачку

2024-11-19 20:26 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        CompletableFuture<List<Hash>> combinedFuture = CompletableFuture.completedFuture(new ArrayList<>());
А у меня инициализация тк в 71 строке этот список, иначе там нужно будет делать инициализацию. Да, со стримами прикольно))

2024-11-19 20:42 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        int capacityFactor = ONE_HUNDRED / cacheProperties.getCapacity();
Всее, я уже устала))

2024-11-19 21:01 UTC, merged