BJS2-42536 решение задачи
CorporationX/url_shortener_service pull request #644
Opened 2024-11-16 09:07 UTC by KarabbasBarabas

BJS2-42537
BJS2-42538
BJS2-42540
BJS2-42541
BJS2-42542
BJS2-42543
BJS2-42544
BJS2-42545

2024-11-16 10:05 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public String generateShorUrl(@Validated @RequestBody UrlDto url) {
опечатался наверное, Short :)

2024-11-16 10:06 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            .createdAt(LocalDateTime.now()) // сам spring значение не подставляет почему-то
попробуй поставить в entity @Temporal(TemporalType.TIMESTAMP) вместе с @CreationTimestamp, должен начать подставлять

2024-11-16 10:07 UTC, soulasphyxia commented on src/main/resources/db/changelog/changeset/V001_create_entities.sql
> +drop table if exists public.hash;
а почему не create if not exists?)

2024-11-16 10:08 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    String url
вроде в задаче просили проверить каким-нибудь образом, что нам передают именно ссылку

2024-11-16 10:12 UTC, soulasphyxia commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public ResponseEntity<Void> getUrl(@PathVariable @NotBlank String shortUrl) {
наверное ты здесь передаешь хэш, а не юрл? немного тяжело понимать как ты это написал. как я думаю, короткий юрл это host/{hash}, например localhost:8080/100000, а 100000 это конкретно хэш, по которому мы эту ссылку и возвращаем. из логики кода я это понял, но по названиям не совсем понятно

2024-11-16 10:57 UTC, SharkB38 approved these changes

2024-11-16 10:57 UTC, SharkB38 commented on lombok.config
> +lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier
Хорош

2024-11-16 10:57 UTC, SharkB38 commented on src/main/java/faang/school/urlshortenerservice/config/executor/TaskExecutorConfig.java
> +    }
Думаешь есть необходимость в двух тредпулах?

2024-11-16 10:57 UTC, SharkB38 commented on src/main/resources/db/changelog/changeset/V001_create_entities.sql
> +);
Мне кажется тут может быть ситуация, когда потеряются освободившиеся кэши, хотя это конечно не критично

2024-11-16 12:37 UTC, soulasphyxia approved these changes

2024-11-16 17:47 UTC, ArstanSubanov approved these changes
Интересная реализация) Оставил свои рекомендации)

2024-11-16 17:47 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            return new RuntimeException(message);
Порекомендовал бы бросать EntityNotFoundException и ловить в GlobalExceptionHandler)

2024-11-16 17:47 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private void fillHashCache(int batchSize) {
Помнишь Влад рассказывал про proxy? По идее из-за этого, при вызове метода fillHashCache в методе checkAndFillHashCache не создаётся транзакция)

2024-11-16 17:47 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/service/CleanerService.java
> +        LocalDateTime timestamp = LocalDateTime.now().toLocalDate().atStartOfDay().minusYears(1);
Посоветовал бы ещё год вынести в конфиг и поменять на дни(365), просто может случится так, что нужно будет удалять старые каждый месяц/полгода и т.д, так получится больше гибкости)

2024-11-17 10:26 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public String generateShorUrl(@Validated @RequestBody UrlDto url) {
ага

2024-11-17 10:31 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            .createdAt(LocalDateTime.now()) // сам spring значение не подставляет почему-то
да, я видимо эту аннотацию с @Timestamp перепутал

2024-11-17 10:33 UTC, KarabbasBarabas commented on src/main/resources/db/changelog/changeset/V001_create_entities.sql
> +drop table if exists public.hash;
удаляю на тот случай, чтобы когда в процессе разработки правки вношу какие-то, констраинт новый добавить, например, то можно было бы этот скрипт запускать и не делать новый скрипт миграции, а так на всякий случай когда уже разработка завершена думаю лучше удаление убрать

2024-11-17 10:49 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    String url
поправил, но сообщение не передаётся в Postman, там в error написано "Bad Request", а не "Incorrect link format".
@mysosnovskaya подскажи, пожалуйста, как поправить

2024-11-17 10:51 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public ResponseEntity<Void> getUrl(@PathVariable @NotBlank String shortUrl) {
Мне наоборот с shortUrl понятней, у нас сервис url_shortner. Он по короткой ссылке выдаёт длинную, и по полученной длинной выдаёт новую короткую

2024-11-17 10:52 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/config/executor/TaskExecutorConfig.java
> +    }
хз, в задаче написано, что у HashCache свой экзекьютор, у HachGenerator свой

2024-11-17 10:53 UTC, KarabbasBarabas commented on src/main/resources/db/changelog/changeset/V001_create_entities.sql
> +);
при удалении таблицы имеешь ввиду? - это на момент разработки было, поправил

2024-11-17 11:01 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            return new RuntimeException(message);
а зачем отдельное исключение делать? у него статус другой будет, не INTERNAL_SERVER_ERROR из handleOthersException?

2024-11-17 11:01 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/CleanerService.java
> +        LocalDateTime timestamp = LocalDateTime.now().toLocalDate().atStartOfDay().minusYears(1);
согласен, так больше гибкости будет

2024-11-17 11:12 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/CleanerService.java
> +        LocalDateTime timestamp = LocalDateTime.now().toLocalDate().atStartOfDay().minusYears(1);
но так, если указать 365, то в случае високосного года логика будет немного не такой, как задумывалась.
А minusYears отработает так как нужно.Не знаю, насколько это важно
<img width="1196" alt="Снимок экрана 2024-11-17 141126" src="https://github.com/user-attachments/assets/9686f57e-eaa0-4ca3-acd7-292c7327fcf9">

2024-11-17 11:28 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            .createdAt(LocalDateTime.now()) // сам spring значение не подставляет почему-то
хотя снова перестало работать, а аннотацию повесил

2024-11-17 11:38 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private void fillHashCache(int batchSize) {
изменил private на public, но всё равно  не создаётся почему-то

2024-11-17 12:30 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            return new RuntimeException(message);
Да, сейчас если юзер отправит запрос get, то если короткой ссылки нету в базе, он получит 500 ошибку, а это ошибка говорит что проблема на стороне сервера, мы говорим юзеру, что проблему у нас, хотя у нас проблем нет, это юзер неправильную короткую ссылку ввёл и нам нужно уведомить его об этом) EntityNotFoundException создавать не нужно, он уже есть в библиотеке jakarta.persistence, его нужно тут просто выбросить, а в GlobalExceptionHandler его словить и вернуть сообщение с кодом 404)

2024-11-17 12:39 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private void fillHashCache(int batchSize) {
Тут дело в том, что все аннотации типа Transactional, Async и т.д не будут работать если вызывать их в том же классе, когда ты вызываешь метод с аннотацией @Transactional из другого класса, например через класс контроллера вызываешь методы сервиса, то по сути ты вызываешь методы не самого сервиса, а proxy объекта, который был создан на основе твоего сервиса и как раз таки прокси объект создаёт транзакции.  Поэтому вызывая метод в том же классе, ты обходишь прокси и напрямую вызываешь методы из-за этого не создаётся транзакция) И да, прокси объекты работают только с public полями)

2024-11-17 12:42 UTC, ArstanSubanov commented on src/main/java/faang/school/urlshortenerservice/service/CleanerService.java
> +        LocalDateTime timestamp = LocalDateTime.now().toLocalDate().atStartOfDay().minusYears(1);
Я думаю это некритично 1 или 2 дня разницы, так как на бизнес-логику приложения это никак не повлияет, ну удалились неиспользованные хэши на день позже, от этого же приложение не перестанет работать)

2024-11-17 12:46 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private void fillHashCache(int batchSize) {
@mysosnovskaya 
Подскажи пожалуйста, почему при выбрасывании  исключения не срабатывает, запушил код с примером

2024-11-17 12:49 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +            return new RuntimeException(message);
да, согласен

2024-11-17 12:57 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private void fillHashCache(int batchSize) {
повесил аннотацию на getHash, все равно не работает

2024-11-17 13:43 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private void fillHashCache(int batchSize) {
вынес private void fillHashCache(int batchSize) в hashGenerator - транзакция заработало, видимо какие-то траблы возникают, когда асинхронно метод с @Transactional запускается

2024-11-17 21:10 UTC, mysosnovskaya requested changes

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/config/HashCacheQueueConfig.java
> +    @Bean
👍

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public ResponseEntity<Void> getUrl(@PathVariable @NotBlank String shortUrl) {
Виталя говорит про то, что shortUrl включает в себя и хост, и порт, и хэш. Это верно. Поэтому если тебе здесь приходит только хэш, то конечно лучше назвать это hash, чтобы никого не смущать) Настаивать не буду, но поправить рекомендую)

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    String url
Видимо, ты так исключение обрабатываешь. Тут какое-то более сложное исключение выбрасывается и его нужно по-особенному обрабатывать. Посмотри, пожалуйста, в других наших микросервисах. Там обработка MethodArgumentsNotValidException и ConstraintViolationsException - вот какое-то из них здесь выбрасывается и в GlobalExcpetionHandler нужно правильно с ним поработать, чтобы вытащить нужное сообщение)

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    @Pattern(regexp = "^http.+", message = "Incorrect link format")
А @URL не подойдет?)

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ConstraintViolationException.class)
А, ну вот оно у тебя. Его только обработать по-хитрому надо

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/model/Hash.java
> +@Data
data с entity нельзя использовать
https://habr.com/ru/companies/haulmont/articles/564682/

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    List<Hash> getHashBatch(int batchSize);
Уже предлагала выше и обосновывала, почему лучше их сразу же и удалить)

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/CleanerService.java
> +    public void clearCache(String hash) {}
Оригинально) Точно работает, проверял?)

2024-11-17 21:10 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        String shorUrl = hashCache.getHash();
Нам сначала нужно проверить, нет ли у нас уже такого же урла в базе. А то зачем нам ещё раз генерировать новый хэш, когда можно использовать уже готовый)

2024-11-18 10:57 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public ResponseEntity<Void> getUrl(@PathVariable @NotBlank String shortUrl) {
Не понял если честно про хост и порт, их же тут нет

2024-11-18 10:58 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java
> +@EnableCaching
добавил

2024-11-18 11:10 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        if (queueHash.size() < maxCacheSize * thresholdFractionSize) {
поправил

2024-11-18 11:11 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +            hashGenerator.fillHashCache(queueHash, batchSize);
согласен, поправил

2024-11-18 11:21 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashGenerator.java
> +        }
поправил

2024-11-18 11:30 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/cache/HashGenerator.java
> +        hashRepository.deleteByIds(hashes);
у меня заполнение кэша и базы стартует в методе hashCache.checkAndFillHashCache(), а он synchronized.
поэтому только один поток может запускать заполнение базы и кэша в приложении

2024-11-18 11:31 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    @Pattern(regexp = "^http.+", message = "Incorrect link format")
добавил

2024-11-18 11:36 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    String url
поправил

2024-11-18 11:36 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ConstraintViolationException.class)
поправил

2024-11-18 11:38 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/model/Hash.java
> +@Data
а у меня же есть @NoArgsConstructor

2024-11-18 11:39 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/model/Hash.java
> +@Data
или все равно не правильно?
поэтому автоматически спринг createdAt не проставляет?

2024-11-18 11:50 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    List<Hash> getHashBatch(int batchSize);
поправил

2024-11-18 11:50 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/CleanerService.java
> +    public void clearCache(String hash) {}
не проверял)
хотел тесты написать, но вот не успеваю

2024-11-18 11:53 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        String shorUrl = hashCache.getHash();
если есть ошибку выкидывать или возвращать значение?

2024-11-18 19:28 UTC, mysosnovskaya requested changes
Жду ещё интеграционных тестов и в следующий раз внимательно проверю покрытие всех основных сценариев. Так что если ещё что-то не дописал - дописывай)

2024-11-18 19:28 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash/HashGenerator.java
> +    @Async("hashGeneratorExecutor")
Рекомендую ознакомиться
https://www.baeldung.com/spring-transactional-async-annotation

2024-11-18 19:28 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/model/Hash.java
> +@Data
Это в целом плохая практика, т.к. Data генерирует методы equals, hashcode, tostring. Конкретно в твоем случае сейчас проблем не будет, но всё равно лучше никогда их вместе не использовать. В статье как раз расписано, какие проблемы могут быть

2024-11-18 19:28 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        delete from hash d
Хорошо, что сделал так, потому что если ты используешь synchronized, то это касается только потоков в одном микросервисе, а у нас может быть запущено несколько экземпляров одного микросервиса и тогда synchronized не поможет)

2024-11-18 19:28 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        String shorUrl = hashCache.getHash();
С Арстаном сегодня как раз этот вопрос обсуждали - возвращать значение) Пользователь же не виноват, что кто-то другой раньше него по этой ссылке сходил.

2024-11-18 19:28 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash/HashFiller.java
> +        }
Мне кажется, что при нашей архитектуре вообще не может быть такого, что список hashes пустой. Если вдруг так оказалось, то значит у нас неверно выстроены параметры (значит генерировать в один момент времени нужно кратно больше). Сейчас это, конечно, костыль. Если хочется эту ситуацию как-то предусмотреть, то можно хотя бы тоже через цикл сделать. Сейчас абсолютно никакого толка от того, что мы 1 хэш добавим, нет. Он исчезнет тут же и опять возникнет точно такая же проблема. Я бы кстати в логи на уровне warn писала о такой ситуации. Но в целом мы храним кэши в базе данных как раз с той целью, чтобы хэши у нас были вообще всегда и если мы забираем оттуда 1000, то положить должны 10_000 или 100_000 (тут надо подбирать параметры, если говорим о реальном продакшне)

2024-11-29 16:46 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/model/Hash.java
> +@Data
убрал @Data

2024-11-29 16:56 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/hash/HashGenerator.java
> +    @Async("hashGeneratorExecutor")
там сказано, что лучше вызывать @Async в @Transactional, чтобы всё работало корректно.Но я не понял, что будет, если навесить эти аннотации на один метод?

2024-11-29 16:56 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +        delete from hash d
понял, спасибо!

2024-11-29 17:15 UTC, KarabbasBarabas commented on src/main/java/faang/school/urlshortenerservice/hash/HashFiller.java
> +        }
поправил

2024-11-30 18:28 UTC, mysosnovskaya approved these changes
Я закрою тебе эту задачу, но с тем комментарием про Transactional + Async разберись, пожалуйста :)

2024-11-30 18:28 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/hash/HashGenerator.java
> +    @Async("hashGeneratorExecutor")
У тебя для метода generateBatch будет создана транзакция, но затем основной код этого метода будет запущен в другом потоке (из-за аннотации Async), а на другой поток транзакция не распространяется)

2024-11-30 18:28 UTC, merged