Unicorn master stream6 varya feature bjs2 42668
CorporationX/url_shortener_service pull request #646
Opened 2024-11-16 10:10 UTC by StepnovaVarvara

2024-11-18 06:20 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +@ToString
ToString лишний

2024-11-18 06:20 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        redisTemplate.expire(url.getHash(), 1, TimeUnit.DAYS);
Можно в настройках указать время жизни добавленного ключа.

2024-11-18 06:20 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +
Transactional?

2024-11-18 06:20 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java
> +    Url toEntity(UrlDto urlDto, String hash);
А просто хэш строкой замапит без mapping?

2024-11-18 16:21 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +@ToString
точно, у меня же data!

2024-11-18 16:22 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +
забыла...

2024-11-18 17:18 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java
> +    Url toEntity(UrlDto urlDto, String hash);
Блин, тебя не поймешь, то делай через маппер, то не делалай!))

2024-11-18 17:57 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java
> +    Url toEntity(UrlDto urlDto, String hash);
))) вопрос не к маперу а по мэпингу.
если передать объект + переменную, он эту переменную смэпит сам без доп аннотаций?

2024-11-18 20:13 UTC, mysosnovskaya requested changes

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    @Pattern(regexp = "^(https?://)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(/[a-zA-Z0-9-._~:/?#@!$&'()*+,;=]*)?$",
Есть аннотация URL, которая именно это и делает)

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java
> +    Url toEntity(UrlDto urlDto, String hash);
Оставляем вопрос открытым)

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlCacheRepository.java
> +    <S extends Url> S save(S entity);
Это зачем?

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +public interface UrlRepository extends JpaRepository<Url, String> {
Я не поняла разницу с UrlCacheRepository

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private final RedisTemplate redisTemplate;
`RedisTemplate<String, String>`

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        Url url = urlRepository.save(urlMapper.toEntity(urlDto, hash));
Сначала бы убедиться, что в базе данных у нас ещё нет короткого урла, соответствующего переданному полному урлу. А то зачем второй раз генерировать новый хэш для того же самого урла?

2024-11-18 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        urlCacheRepository.save(url);
Это не поняла, что такое urlCacheRepository?

2024-11-19 02:54 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java
> +    Url toEntity(UrlDto urlDto, String hash);
Аааа... Ваши вопросы в пол строчки фиг разберешь, блин!))) Да все прекрасно мапится, думаю, потому что названия полей совпадают. Тоже этим вопросом задавалась! Тестик на это написала + в логах при проверке все правильно выводится

2024-11-19 18:08 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java
> +    @Pattern(regexp = "^(https?://)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(/[a-zA-Z0-9-._~:/?#@!$&'()*+,;=]*)?$",
Да, я про нее вспомнила уже после того как скинула на ревью)

2024-11-20 02:52 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlCacheRepository.java
> +    <S extends Url> S save(S entity);
Короче, у нас по задаче написано: "UrlCacheRepository сохраняет данные в Redis. Это spring bean." Я пыталась это дело сделать, но у меня постоянно вылетала ошибка, что спринг не может создать два одинаковых бина UrlCacheRepository, тк он пытается создать для  JPA, а второй для редиса. Короче, я уже два дня на эту задачу потратила и предлагаю убрать этот компонент. Сейчас редис как кеш у меня работает!)

2024-11-20 02:53 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +public interface UrlRepository extends JpaRepository<Url, String> {
ответила выше

2024-11-20 02:53 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    private final RedisTemplate redisTemplate;
поменяла

2024-11-20 02:53 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        urlCacheRepository.save(url);
ответила выше

2024-11-20 03:13 UTC, StepnovaVarvara commented
Маша, я сюда из задачки с хешгенератором, которую мы закроем, перенесла тесты на этот класс

2024-11-20 17:23 UTC, mysosnovskaya requested changes
Ещё конфликты поправь и будем заканчивать с этой задачей)

2024-11-20 17:23 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java
> +import org.springframework.cache.annotation.EnableCaching;
Импорт есть, а аннотации нет =)

2024-11-20 17:23 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +        redisTemplate.opsForValue().set(url.getHash(), url);
Это должно быть в отдельном классе-кэше. Это не ответственность самого сервиса

2024-11-20 17:23 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlCacheRepository.java
> +public interface UrlCacheRepository extends CrudRepository<Url, String> {
Тебе этот класс в виде jpa репозиотрия точно не нужен) Его можно было бы сделать редис-репозиторием (тогда другой импорт нужен, не из .data.repository), но тоже необязательно, это просто как вариант. Тебе лучше просто сделать свою реализацию, где ты сама пропишешь все методы для взаимодействия с редисом. Класс можно назвать HashCache или оставить UrlCacheRepository

2024-11-23 09:17 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlCacheRepository.java
> +public interface UrlCacheRepository extends CrudRepository<Url, String> {
переделала

2024-11-23 09:39 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java
> +import org.springframework.cache.annotation.EnableCaching;
упс))

2024-11-23 16:21 UTC, mysosnovskaya approved these changes

2024-11-23 16:21 UTC, merged