feature-BJS2-42653: Джоб для освобождения неиспользуемых хэшей
CorporationX/url_shortener_service pull request #653
Opened 2024-11-16 14:21 UTC by StepnovaVarvara

2024-11-18 09:46 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +            WHERE created_at < NOW() - INTERVAL '1 year'
год вынести в конфиг

2024-11-18 09:46 UTC, GusevVrn commented on src/main/java/faang/school/urlshortenerservice/service/cleaner/CleanerScheduler.java
> +    @Async("executor")
Нужен ли в текущей реализации явный async.
может быть вынести логику всю в сервис и над этим методом повесить transactional

2024-11-18 18:14 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +            WHERE created_at < NOW() - INTERVAL '1 year'
гатова)

2024-11-18 20:00 UTC, mysosnovskaya requested changes

2024-11-18 20:00 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    @Async("executor")
Писала в другом ПРе про это)

2024-11-18 20:00 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +    List<String> getHashesAndDeleteOldUrls(@Param("years") int years);
old -> expired

2024-11-18 20:00 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    public void moderateDB() {
releaseExpiredHashes

2024-11-19 02:39 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    @Async("executor")
Я думала, что тут явно другой поток должен был трудиться

2024-11-19 02:40 UTC, StepnovaVarvara commented on src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java
> +    List<String> getHashesAndDeleteOldUrls(@Param("years") int years);
поправила

2024-11-19 19:58 UTC, mysosnovskaya approved these changes

2024-11-19 19:58 UTC, mysosnovskaya commented on src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java
> +    @Transactional
То, что async + Transactional нельзя вешать вместе, ещё не говорит о том, что метод нельзя выполнить одновременно и асинхронно, и в транзакции =) Я статью кидала, там как раз подробнее про это написано. Ты просто удалила Async, но у меня нет уверенности, что ты разобралась, почему так вешать нельзя и как делать, если всё-таки нужно)

2024-11-19 19:58 UTC, merged