BJS2-43076 Готовый шортнер
CorporationX/url_shortener_service pull request #656
Opened 2024-11-16 16:08 UTC by cemeh666

2024-11-18 19:31 UTC, 20cognosce requested changes

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/HashAsyncConfig.java
> +    private int maxPoolSize;
Что это за цифры

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/exception/handler/UrlExceptionHandler.java
> +    @ExceptionHandler(ApiException.class)
Дублируется код, сделай один хэндлер, и внутри него в зависимости от класса ошибки обрабатывай по-разному и статусы присваивай разные

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +                .toList());
Вынеси в отдельный список

2024-11-18 19:31 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    maxPoolSize: 1
Executors.singleThreadPoolExecutor()?

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private final Queue<String> hashes = new LinkedBlockingQueue<>();
Можно Concurrent вместо Blocking?

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private long minPercentHashes;
Почему у тебя тут числа указаны, если ты их из конфига должен брать?

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        hashes.addAll(hashGenerator.getHashes(capacity));
Почему тут нет флага, о том что идет генерация

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        double cacheFullPercentage = 100.0 / capacity * hashes.size();
Почему сразу нельзя асинхронный поток запустить, первой строчкой

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                        });
Когнитивно перегруженный блок кода, зачем тебе дожидаться асинхронной генерации, чтобы выполнить добавление в очередь коллбеком?

Правильнее сразу сходить в базу и забрать хэши, и в фоне запустить генерацию.

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +    @Value("${generator.batch.size:100000}")
.

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/HashAsyncConfig.java
> +        executor.setMaxPoolSize(maxPoolSize);
А зачем тебе столько потоков-то, если у тебя флаг стоит на то, чтобы одновременно только один асинхронный поток мог генерировать в базу хэши?

2024-11-18 19:31 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        return hashes.stream().map(Hash::getHash).toList();
Может не надо везде перемапливать одно в другое? Работай с сущностью

2024-11-19 14:09 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private final Queue<String> hashes = new LinkedBlockingQueue<>();
можно. она даже быстрее. единственное, что мне не понравилось - это

> Работает быстрее, чем блокирующие очереди, так как использует ненастоящие блокировки (lock-free).

2024-11-19 14:10 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +    private long minPercentHashes;
это дефолтные значения, если в конфиге не указать

2024-11-19 14:15 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        hashes.addAll(hashGenerator.getHashes(capacity));
так это запускается синхронно с включением приложения и приложение не запустится до завершения. 
флаг тут бессмысленен

2024-11-19 14:36 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +                        });
переделал

2024-11-19 14:37 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/config/HashAsyncConfig.java
> +        executor.setMaxPoolSize(maxPoolSize);
убрал

2024-11-19 14:47 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        return hashes.stream().map(Hash::getHash).toList();
зачем нам в локальном кеше хранить объект Hash?
чтобы потом из него брать .getHash()?
по памяти явно дешевле хранить Sthing а не сущность Hash

2024-11-19 15:01 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +            generateBatch();
этот метод вызывается в 2 случаях
1) При старте приложения (когда БД пустая) и нужно сгенерировать хеши синхронно и мы ждём только при старте
2) При догенерации и этот запуск вызывается асинхронно и пользователь не ждёт

> Хотели достать хэши из базы и в итоге зависли на генерации

Хотели достать хэши из базы - достал, если их меньше чем нужно, то догенерируем и это никак не скажется на производительности так как метод вызывается в 2 случаях

2024-11-21 09:07 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/cache/HashCache.java
> +        hashes.addAll(hashGenerator.getHashes(capacity));
конструктор тут не подойдёт. при его вызове ещё не заполнены переменные через @Value

2024-11-21 09:51 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        List<String> hashes = urlRepository.getAndDeleteUrlsByDate(expireDate);
сохранять в БД dateExpired плохой вариант, так как могут условия поменяться и захотят удалять все ссылки старше месяца например, а в БД уже стоит год.
как по мне лучше этот вариант

2024-11-21 10:07 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        urlCacheRepository.deleteHashes(hashes);
для редиса нет конечно. тут транзакция нужна, чтобы если после удаления сохранение выбросит ошибку, то удаление откатится

2024-11-21 11:05 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java
> +        return hash.replaceFirst("^0+", "");
да. переделал немного

2024-11-21 11:06 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/config/HashAsyncConfig.java
> +    private int maxPoolSize;
убрал уже

2024-11-21 11:24 UTC, cemeh666 commented on src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java
> +        if (hashes.size() < amount) {
сделал так.
Проверяем есть ли в БД столько хешей, сколько нам нужно
если нет, то генерируем (сохраняем) и возвращаем
если есть, то возвращаем из БД

2024-11-23 20:11 UTC, 20cognosce approved these changes

2024-11-23 20:11 UTC, merged