Создание оригинальной ссылки
CorporationX/url_shortener_service pull request #67
Opened 2023-10-26 14:29 UTC by ringoway

2023-10-26 15:53 UTC, ringoway commented
По какой-то причине идёт вечный запуск сервиса

2023-10-28 16:33 UTC, kkkooolllyyyaaa requested changes
👌 , пару минорных комментов

2023-10-28 16:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +    public void hashClear() {
Лучше назвать что-то вроде освободить, или вернуть, а не очистить. Ты же сохраняешь в HashRepository

2023-10-28 16:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/repository/RedisCacheRepository.java
> +            log.warn("Hash {} found in cache", hash);
почему warn?

2023-10-28 16:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public ResponseEntity<String> getUrl(@RequestBody UrlDto urlDto) {
Get, не?

2023-10-28 16:33 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +                log.warn("Queue is full");
break можно

2023-10-29 16:57 UTC, kkkooolllyyyaaa approved these changes
👍

2023-10-29 16:57 UTC, merged