BJS2-43039 Шортнер
CorporationX/url_shortener_service pull request #670
Opened 2024-11-17 09:53 UTC by ilu23ilu23

Созданы все классы по условиям, так же тесты

2024-11-19 18:26 UTC, 20cognosce requested changes

2024-11-19 18:26 UTC, 20cognosce commented on src/main/resources/application.yaml
> +  queueCapacity: 50
Ну один поток всего одновременно генерит хэши для базы, один
Зачем вам целый пул
singleThreadPoolExecutor()

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        }
Это должно быть невозможно, почему

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +        List<Url> oldUrls = urlRepository.findAllByCreatedAtBefore(cutoffDate);
1 - magic number

Можно сразу сохранять в БД дату жизни короткой ссылки

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +        List<String> freedHashes = oldUrls.stream().map(Url::getHash).collect(Collectors.toList());
Не писать так

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +        List<Hash> hashEntities = freedHashes.stream().map(Hash::new).toList();
И так

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +    @Transactional
Нет, тут транзакция не поможет
Нашел - сохранил - удалил, не прокатит, нужны пессимистичные блокировки на поиск тогда, иначе юзеры будут ходить по этой ссылке в момент удаления

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java
> +    @Transactional
Зачем тебе транзакция тут

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/ExecutorConfig.java
> +    }
Тебе нужен только newSingleThreadExecutor на наполнение базы хэшами, всё

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        fillCacheSync();
Почему не в конструкторе
Почему блокирующая

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +    private Queue<String> hashQueue;
final

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +    private final ReentrantLock lock = new ReentrantLock();
Можно было бы и атомиком обойтись

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        }
?) 
Как такое может быть, этого быть не должно

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        }
???

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        }
А можно просто запустить поток и в нём проверки все делать, не заставляя на получении хэша считать наполнение кэша

Только учти, что нужно тред пул из одного потока, и если он уже занят - новые таски нужно просто игнорить, а не забивать его очередь задачь до OOM

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +    private void fillCacheSync() {
Зачем есть этот метод вообще, если это просто performCacheFill в локах?

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        }
Столько try catch finally if else убивают читаемость и это выглядит плохо

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +                log.info("Asynchronous cache fill completed. Current size: {}", hashQueue.size());
не в info, debug

2024-11-19 18:26 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +    public void fillCacheAsync() {
Ну и этот метод так же просто вызывает performCacheFill

2024-11-29 15:03 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/url_shortener_V001__create_tables_hash_url_sequence.sql
> +    created_at TIMESTAMP NOT NULL
Это уже так с форматированием

2024-11-29 15:47 UTC, ilu23ilu23 commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        }
Понимаю, но в текущей реализации от этого мне не уйти(

2024-12-01 10:15 UTC, 20cognosce requested changes

2024-12-01 10:15 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/url_shortener_V001__create_tables_hash_url_sequence.sql
> +    START WITH 1000
Какая длина будет у твоих ссылок? Сначала 2 символа, потом 3, потом 4 и т.д.?
Где фиксированная длина

2024-12-01 10:15 UTC, 20cognosce commented on src/main/resources/application.yaml
> +  queueCapacity: 50
Для кого осталась эта настройка

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +    private Long lifeLinks;
Что значит эта переменная, как понять этот нейминг

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +        LocalDateTime cutoffDate = LocalDateTime.now().minusYears(lifeLinks);
lifeLinks = года жизни ссылки? 
Я говорил дату экспирации хранить для каждый ссылки

Либо дай понятное название своим пропертям, и одних только лет недостаточно - месяцы, дни?

Можно сразу в днях по крайней мере

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java
> +        freedHashes.forEach(urlCacheRepository::delete);
Наверно сначала надо из кэша удалить, сразу после удаления из базы

А потом только класть освобожденные в таблицу доступных хэшей

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +            hashGenerator.generateBatch();
Почему ты всегда генерируешь для базы фиксированный размер, а забираешь динамический
Получается ситуация, когда взял 1, а сгенерил 100, и так до бесконечности

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        fillCacheAsync();
Почему ты никак не учитываешь текущее состояние базы, требуется ли генерация вообще
Должны быть 3 случае
- в базе критически мало хэшей
- в базе оптимально хэшей
- в базе избыток хэшей

И от того принимать решение по генерации

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java
> +    @Transactional
Что здесь она делает

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java
> +    """, nativeQuery = true)
Сначала nativeQuery = true, потом запрос

Зачем тебе два селекта? Внутри IN можно то же самое записать, что ты вынес в WITH cte AS

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +    @Transactional
Зачем

2024-12-01 10:15 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +            """, nativeQuery = true)
То же самое

2024-12-01 11:50 UTC, ilu23ilu23 commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +            hashGenerator.generateBatch();
Чтобы гарантировать, что в базе данных всегда будет запас хэшей, так по условию

2024-12-01 11:57 UTC, ilu23ilu23 commented on src/main/java/faang/school/urlshortenerservice/service/HashCache.java
> +        fillCacheAsync();
Опять же, чем больше хэшей в бд, тем лучше, ничего страшного, если мы нагенерим еще 300 хэшей прозапас)

2024-12-01 18:41 UTC, 20cognosce approved these changes

2024-12-01 18:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +                .fromCurrentContextPath() + hash;
В сервисе надо это делать, ты метод даже назвал createShortUrl, а не createHash

2024-12-01 18:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java
> +        return String.format("%5s", sb.reverse()).replace(' ', '0');
00012345 -> 54321000
%5s - это как дальше заформатируется? Первые 5 символов?
А затем нули почему заменяем на пробелы?

Мутная строчка кода

2024-12-01 18:44 UTC, merged