Url Shortener full task BJS2-43038-BJS2-43053-BJS2-43057-BJS2-43063-BJS2-43064-BJS2-43066-BJS2-43067-BJS2-43068-BJS2-43070-BJS2-43069
CorporationX/url_shortener_service pull request #674
Opened 2024-11-17 11:59 UTC by vestmen

2024-11-19 17:47 UTC, 20cognosce requested changes

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    @PostMapping()
Пустые скобки не нужны

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public String createHash(@RequestParam @ValidUrl String url) {
В ResponseEntity оборачивай
Зачем написал свою аннотацию для валидации когда есть готовые???

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +    public RedirectView getUrl(@PathVariable String hash) {
RedirectView не deprecated случайно?
Лучше ReponseEntity со статусом 3ХХ

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/entity/Hash.java
> +@Entity
Сначала JPA, потом lombok и прочие фантики

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    private LocalDateTime createdAt = LocalDateTime.now();
Что это за присвоение

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/Base62Encoder.java
> +public class Base62Encoder {
Где настройка длины хэша?

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/validator/CustomUrlValidator.java
> +public class CustomUrlValidator implements ConstraintValidator<ValidUrl, String> {
Так в принципе не так плохо
Если бы аспект сделал - тогда точно переделывать, ну а так, пойдёт

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/validator/CustomUrlValidator.java
> +            InetAddress address = InetAddress.getByName(url.getHost());
Что это такое

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/validator/CustomUrlValidator.java
> +        return true;
Вот этот блок кода выглядит не очень
Разве создания урла через класс не достаточно? Он ошибки не кидает?

2024-11-19 17:47 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__url-shortener-service_url_hashes_sequence.sql
> +    INCREMENT BY 1;
У тебя тоже длина короткой ссылки будет расти для новых пользователей

2024-11-19 17:47 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__url-shortener-service_url_hashes_sequence.sql
> +    hash VARCHAR(6) NOT NULL PRIMARY KEY
Как ты вообще создашь кэш из 6-ти символов, если тебе пришла единица для кодировки?
Ты первой короткой ссылкой отдашь url/0 ? Ты тестил это?)

2024-11-19 17:47 UTC, 20cognosce commented on src/test/java/faang/school/urlshortenerservice/service/generator/Base62EncoderTest.java
> +        List<String> expected = List.of("8G", "9G", "AG", "BG", "CG", "DG", "EG", "FG", "GG", "HG", "IG");
Это неправильно

2024-11-19 17:47 UTC, 20cognosce commented on src/test/java/faang/school/urlshortenerservice/service/generator/Base62EncoderTest.java
> +        List<String> expected = List.of("8G", "9G", "AG", "BG", "CG", "DG", "EG", "FG", "GG", "HG", "IG");
Вы друг у друга тесты копируете?)
Или была такая заготовка

2024-11-19 17:47 UTC, 20cognosce commented on src/test/java/faang/school/urlshortenerservice/service/generator/HashGeneratorTest.java
> +        when(base62Encoder.encode(uniqueNumbers)).thenReturn(encodedHashes);
Что тогда мы тестируем

2024-11-19 17:47 UTC, 20cognosce commented on src/test/java/faang/school/urlshortenerservice/service/generator/HashGeneratorTest.java
> +        when(base62Encoder.encode(uniqueNumbers)).thenReturn(encodedHashes);
Хэш Генератор мокает Шифратор, ну....

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        List<Hash> oldUrls = urlRepository.deleteOldUrlsAndGetFreedHashes(minusYear);
А можно при создании короткой ссылки в базу сразу писать срок её жизни, а не заниматься этим?

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +@RequestMapping("url_shortener")
Почему тут у тебя такой base_url, а в пропертях static_address: "http://sh.c/"?

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    public String getUrl(String hash) {
Сейчас это не работает

Если я выдам себе короткую ссылку по vk.com, то получу
http://sh.c/0

И затем если я перейду по http://sh.c/0, то сервис просто выдаст ошибку

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        return staticAddress + hash;
Ты точно тестил?

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        urlCacheRepository.saveUrl(url, urlTtlAtCache);
Логика правильная, но можно без опшиналов?
И берез переприсвоение в if блоке

Будет попроще код

if (! .isEmpty()) { 
return ...
}

var url = urlRepository.find().orElseThrow()
return url;

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java
> +    List<Hash> deleteOldUrlsAndGetFreedHashes(LocalDateTime date);
Орфография
И можно короче

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
> +                    ) RETURNING hash
Форматирование криво

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +    }
Почему не в конструкторе
Почему блокирующая очередь
Почему не выставляется флаг генерации

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +        if (running.compareAndSet(false, true) && !isEnoughHashes()) {
если не выполнится условие isEnoughHashes, то ты навсегда выставил running в true

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +    private Queue<String> hashes;
final

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +                    .thenRun(() -> running.set(false));
А можно одной строчкой просто запустить асинхронную проверку со всей необходимой генерацией, а второй строчкой просто достать из очереди?

В методе getHash не должно быть ничего другого, никаких вычислений

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/HashGenerator.java
> +    @Transactional
Для чего транзакция

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/HashGenerator.java
> +    @Transactional
Для чего транзакция

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/HashGenerator.java
> +    }
Нет, если у тебя упал хэш - ты сразу достаешь из базы, и затем в фоне запускаешь генерацию для базы

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/HashGenerator.java
> +        if (hashes.size() < amount) {
Что это такое, этого не должно быть в природе

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/HashGenerator.java
> +public class HashGenerator {
Я уже это видел точь-в-точь у Семёна
https://github.com/CorporationX/url_shortener_service/pull/656/files

Это такой разбор задачи?

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/generator/HashGenerator.java
> +            generateHashesAsync();
Всё то же самое уже написал Семёну, посмотри его ревью

2024-11-19 17:47 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/config/executor/ExecutorServiceConfig.java
> +        return executor;
У тебя одновременно только один поток всегда генерирует хэши и кладёт их в базу, зачем это всё
Executors.singleThreadPoolExecutor();

2024-11-24 15:24 UTC, vestmen commented on src/main/resources/db/changelog/changeset/V001__url-shortener-service_url_hashes_sequence.sql
> +    hash VARCHAR(6) NOT NULL PRIMARY KEY
последоватьльность начинается с 1, 0 никогда не было бы. Но я уже поправил, чтобы всегда точно выдавало 6 символов

2024-11-24 16:13 UTC, vestmen commented on src/main/java/faang/school/urlshortenerservice/service/generator/Base62Encoder.java
> +public class Base62Encoder {
как мы обсудили кэш из 6 символов будет при значении от 62^5 до 62^6

2024-11-26 16:41 UTC, 20cognosce approved these changes

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/controller/UrlController.java
> +                                 @URL(message = "Invalid URL format") String url) {
Не очень это красиво
А нужны ли очевидные сообщения

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java
> +    List<Hash> deleteAndGetOldLines();
Line - это кто?

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/entity/Url.java
> +    private LocalDateTime deletedAt;
expirationDate

deletedAt - удалён в
Прошедшее время, сбивает с толку

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +        log.info("Url by hash {} not found at the cache", hash);
Этот лог не несёт никакой смысловой нагрузки, так как ниже есть еще один лог о том же

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/UrlService.java
> +    @Value("${scheduler.urls_life_time_days}")
Это не в настройках шедулера, а в настройках ссылки должно быть

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +        hashGenerator.generateHashesAsync();
Это нужно только если в базе мало хэшей, а не всегда

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +    private void initHashes() {
В целом логика близка к целевой, но не совсем
Должно быть 3 условие:
- в базе критично мало, нужна генерация
- в базе достаточно, можно взять, но генерация всё равно нужна
- в базе избыток хэшей, просто берём

2024-11-26 16:41 UTC, 20cognosce commented on src/main/java/faang/school/urlshortenerservice/service/cache/HashCache.java
> +                    .thenRun(() -> running.set(false));
running.set(false) должно быть в блоке finally, иначе при ошибки асинхронной генерации мы зависнем навсегда

2024-11-26 16:41 UTC, merged